<?php

namespace YayMail\TemplateLibrary\Templates\Processing;

use YayMail\Abstracts\BaseTemplate;
use YayMail\Elements\BillingAddress;
use YayMail\Elements\Button;
use YayMail\Elements\Column;
use YayMail\Elements\ColumnLayout;
use YayMail\Elements\Divider;
use YayMail\Elements\Footer;
use YayMail\Elements\Heading;
use YayMail\Elements\Logo;
use YayMail\Elements\OrderDetails;
use YayMail\Elements\ShippingAddress;
use YayMail\Elements\Text;
use YayMail\Utils\SingletonTrait;

/**
 * Blue Receipt template for customer_processing_order email.
 * Generated by tools/yaymail-template-gen — review/tweak values as needed.
 */
class BlueReceipt extends BaseTemplate {
    use SingletonTrait;

    public function __construct() {
        parent::__construct();
        $this->id          = 'processing_order_v17';
        $this->email_type  = 'customer_processing_order';
        $this->name        = 'Blue Receipt';
        $this->description = 'Clean notification for store owners.';
        $this->categories  = [ 'Classic' ];
        $this->access      = 'free';
        $this->elements    = [
            Logo::get_object_data(
                [
                    'padding'          => [
                        'top'    => '24',
                        'right'  => '50',
                        'bottom' => '16',
                        'left'   => '50',
                    ],
                    'background_color' => '#ffffff',
                    'src'              => 'https://images.wpbrandy.com/uploads/blue-woo-logo.png',
                    'align'            => 'center',
                    'width'            => 95,
                    'url'              => '#',
                    'alt'              => 'Store logo',
                ]
            ),
            ColumnLayout::get_object_data(
                1,
                [
                    'children'               => [
                        Column::get_object_data(
                            100,
                            [
                                'children' => [
                                    Heading::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => '12',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'border'      => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'font_family' => '"Outfit", "DM Sans", sans-serif',
                                            'text_color'  => '#1a1a1a',
                                            'rich_text'   => '<h1 style="font-size:30px;font-weight:300;line-height:normal;margin:0px;color:inherit"><h1 style="font-size:36px;font-weight:700;line-height:1.15 !important;margin:0;color:#000000">New Order Received</h1></h1>',
                                        ]
                                    ),
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => '0',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'border'      => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'font_family' => '"Outfit", "DM Sans", sans-serif',
                                            'text_color'  => '#1a1a1a',
                                            'rich_text'   => '<p><span style="font-size: 14px">Order #[yaymail_order_id is_plain="true"] • Placed on [yaymail_order_date]</span></p><p><span style="font-size: 14px">Status: Processing</span></p>',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'column_width'           => [],
                    'column_spacing'         => '0',
                    'responsive_on_mobile'   => false,
                    'vertical_align'         => 'top',
                    'padding'                => [
                        'top'    => '40',
                        'right'  => 30,
                        'bottom' => '40',
                        'left'   => 30,
                    ],
                    'border'                 => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'          => [
                        'top_left'     => 10,
                        'top_right'    => 10,
                        'bottom_left'  => 10,
                        'bottom_right' => 10,
                    ],
                    'background_color'       => '#ffffff',
                    'background_image'       => [
                        'url'        => 'https://images.wpbrandy.com/uploads/bluereceipt-background.png',
                        'position'   => 'bottom_right',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'no-repeat',
                        'size'       => 'cover',
                    ],
                    'inner_border_radius'    => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'inner_background_color' => '#ffffff00',
                ]
            ),
            Text::get_object_data(
                [
                    'padding'          => [
                        'top'    => '24',
                        'right'  => 30,
                        'bottom' => '8',
                        'left'   => 30,
                    ],
                    'background_color' => '#ffffff',
                    'border'           => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'font_family'      => '"Outfit", "DM Sans", sans-serif',
                    'text_color'       => '#1a1a1a',
                    'rich_text'        => '<p><span style="font-size: 18px"><strong>Hi admin</strong></span><span style="font-size: 18px">,</span></p>
                        <p><span style="font-size: 16px">Great news—you\'ve received a new order from <strong>[yaymail_billing_first_name] [yaymail_billing_last_name]</strong>. Review the details below and begin processing it.</span></p>',
                ]
            ),
            ColumnLayout::get_object_data(
                2,
                [
                    'children'               => [
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    Button::get_object_data(
                                        [
                                            'padding'      => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => '0',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff',
                                            'button_type'  => 'default',
                                            'align'        => 'center',
                                            'width'        => '100%',
                                            'custom_width' => '50',
                                            'height'       => '21',
                                            'button_padding' => [
                                                'top'    => '12',
                                                'right'  => '20',
                                                'bottom' => '12',
                                                'left'   => '20',
                                            ],
                                            'button_background_color' => '#02b7ff',
                                            'text_color'   => '#ffffff',
                                            'border'       => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'border_radius' => [
                                                'top_left' => '30',
                                                'top_right' => '30',
                                                'bottom_right' => '30',
                                                'bottom_left' => '30',
                                            ],
                                            'text'         => 'View Order',
                                            'url'          => '[yaymail_order_url]',
                                            'font_size'    => '16',
                                            'weight'       => '600',
                                            'font_family'  => 'Arial, Helvetica, sans-serif',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    Button::get_object_data(
                                        [
                                            'padding'      => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => '0',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff',
                                            'button_type'  => 'default',
                                            'align'        => 'center',
                                            'width'        => '100%',
                                            'custom_width' => '50',
                                            'height'       => '21',
                                            'button_padding' => [
                                                'top'    => '12',
                                                'right'  => '20',
                                                'bottom' => '12',
                                                'left'   => '20',
                                            ],
                                            'button_background_color' => '#ffffff',
                                            'text_color'   => '#1a1a1a',
                                            'border'       => [
                                                'side'  => 'all',
                                                'width' => 2,
                                                'style' => 'solid',
                                                'color' => '#1a1a1a',
                                            ],
                                            'border_radius' => [
                                                'top_left' => '30',
                                                'top_right' => '30',
                                                'bottom_right' => '30',
                                                'bottom_left' => '30',
                                            ],
                                            'text'         => 'Contact Customer',
                                            'url'          => '[yaymail_site_url]',
                                            'font_size'    => '16',
                                            'weight'       => '600',
                                            'font_family'  => 'Arial, Helvetica, sans-serif',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'column_width'           => [],
                    'column_spacing'         => '12',
                    'responsive_on_mobile'   => false,
                    'vertical_align'         => 'top',
                    'padding'                => [
                        'top'    => '16',
                        'right'  => 30,
                        'bottom' => '16',
                        'left'   => 30,
                    ],
                    'border'                 => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'          => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'background_color'       => '#ffffff',
                    'background_image'       => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                    'inner_border_radius'    => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'inner_background_color' => '#ffffff00',
                ]
            ),
            ColumnLayout::get_object_data(
                1,
                [
                    'children'               => [
                        Column::get_object_data(
                            100,
                            [
                                'children' => [
                                    OrderDetails::get_object_data(
                                        [
                                            'rich_text'    => '[yaymail_order_details]',
                                            'payment_instructions' => '[yaymail_payment_instructions]',
                                            'padding'      => [
                                                'top'    => '15',
                                                'right'  => 20,
                                                'bottom' => '15',
                                                'left'   => 20,
                                            ],
                                            'background_color' => '#fafafa',
                                            'border'       => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'layout_type'  => 'modern',
                                            'title'        => '<div><span style="font-size: 24px;font-weight: 600">Order Summary</span></div>',
                                            'title_color'  => '#3d2d21',
                                            'text_color'   => '#3d2d21',
                                            'border_color' => '#e5e5e5',
                                            'font_family'  => '"Outfit", "DM Sans", sans-serif',
                                            'table_content_font_size' => '14',
                                            'table_heading_font_size' => 16,
                                            'show_table_header' => true,
                                            'product_title' => 'PRODUCT',
                                            'cost_title'   => 'COST',
                                            'quantity_title' => 'QUANTITY',
                                            'price_title'  => 'PRICE',
                                            'cart_subtotal_title' => 'Subtotal:',
                                            'payment_method_title' => 'Payment method:',
                                            'order_total_title' => 'Total:',
                                            'order_note_title' => 'Note:',
                                            'shipping_title' => 'Shipping: [yaymail_shipping_method]',
                                            'discount_title' => 'Discount:',
                                            'custom_footer_rows' => [],
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'column_width'           => [],
                    'column_spacing'         => '0',
                    'responsive_on_mobile'   => false,
                    'vertical_align'         => 'top',
                    'padding'                => [
                        'top'    => 20,
                        'right'  => 30,
                        'bottom' => 5,
                        'left'   => 30,
                    ],
                    'border'                 => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'          => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'background_color'       => '#ffffff',
                    'background_image'       => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                    'inner_border_radius'    => [
                        'top_left'     => 10,
                        'top_right'    => 10,
                        'bottom_left'  => 10,
                        'bottom_right' => 10,
                    ],
                    'inner_background_color' => '#ffffff00',
                ]
            ),
            ColumnLayout::get_object_data(
                2,
                [
                    'children'               => [
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    ColumnLayout::get_object_data(
                                        1,
                                        [
                                            'children'     => [
                                                Column::get_object_data(
                                                    100,
                                                    [
                                                        'children' => [
                                                            ShippingAddress::get_object_data(
                                                                [
                                                                    'padding' => [
                                                                        'top'  => '15',
                                                                        'right' => '50',
                                                                        'bottom' => '15',
                                                                        'left' => '50',
                                                                    ],
                                                                    'background_color' => '#fafafa',
                                                                    'layout_type' => 'modern',
                                                                    'title_color' => '#1a1a1a',
                                                                    'text_color' => '#1a1a1a',
                                                                    'border_color' => '#e5e5e5',
                                                                    'font_family' => '"Outfit", "DM Sans", sans-serif',
                                                                    'title'   => '<div><span style="font-size: 18px;font-weight: 600">Shipping Address</span></div>',
                                                                    'shipping_content_font_size' => '14',
                                                                    'shipping_content_alignment' => 'left',
                                                                    'shipping_content_text_format' => [
                                                                        'bold' => false,
                                                                        'italic' => false,
                                                                        'underline' => false,
                                                                    ],
                                                                    'rich_text' => '[yaymail_shipping_address]',
                                                                ]
                                                            ),
                                                        ],
                                                        'border'   => [
                                                            'side' => 'none',
                                                            'width' => '1',
                                                            'style' => 'solid',
                                                            'color' => '#e5e5e5',
                                                            'custom' => [
                                                                'top'  => '1',
                                                                'right' => '1',
                                                                'bottom' => '1',
                                                                'left' => '1',
                                                            ],
                                                        ],
                                                    ]
                                                ),
                                            ],
                                            'column_width' => [],
                                            'column_spacing' => '0',
                                            'responsive_on_mobile' => false,
                                            'vertical_align' => 'top',
                                            'padding'      => [
                                                'top'    => '15',
                                                'right'  => '0',
                                                'bottom' => '15',
                                                'left'   => '0',
                                            ],
                                            'border'       => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'border_radius' => [
                                                'top_left' => 0,
                                                'top_right' => 0,
                                                'bottom_left' => 0,
                                                'bottom_right' => 0,
                                            ],
                                            'background_color' => '#ffffff00',
                                            'background_image' => [
                                                'url'      => '',
                                                'position' => 'default',
                                                'x_position' => 0,
                                                'y_position' => 0,
                                                'repeat'   => 'default',
                                                'size'     => 'default',
                                            ],
                                            'inner_border_radius' => [
                                                'top_left' => 10,
                                                'top_right' => 10,
                                                'bottom_left' => 10,
                                                'bottom_right' => 10,
                                            ],
                                            'inner_background_color' => '#ffffff00',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    ColumnLayout::get_object_data(
                                        1,
                                        [
                                            'children'     => [
                                                Column::get_object_data(
                                                    100,
                                                    [
                                                        'children' => [
                                                            BillingAddress::get_object_data(
                                                                [
                                                                    'padding' => [
                                                                        'top'  => '15',
                                                                        'right' => '50',
                                                                        'bottom' => '15',
                                                                        'left' => '50',
                                                                    ],
                                                                    'background_color' => '#fafafa',
                                                                    'layout_type' => 'modern',
                                                                    'title_color' => '#1a1a1a',
                                                                    'text_color' => '#1a1a1a',
                                                                    'border_color' => '#e5e5e5',
                                                                    'font_family' => '"Outfit", "DM Sans", sans-serif',
                                                                    'title'   => '<div><span style="font-size: 18px;font-weight: 600">Billing Address</span></div>',
                                                                    'billing_content_font_size' => '14',
                                                                    'billing_content_alignment' => 'left',
                                                                    'billing_content_text_format' => [
                                                                        'bold' => false,
                                                                        'italic' => false,
                                                                        'underline' => false,
                                                                    ],
                                                                    'rich_text' => '[yaymail_billing_address]',
                                                                ]
                                                            ),
                                                        ],
                                                        'border'   => [
                                                            'side' => 'none',
                                                            'width' => '1',
                                                            'style' => 'solid',
                                                            'color' => '#e5e5e5',
                                                            'custom' => [
                                                                'top'  => '1',
                                                                'right' => '1',
                                                                'bottom' => '1',
                                                                'left' => '1',
                                                            ],
                                                        ],
                                                    ]
                                                ),
                                            ],
                                            'column_width' => [],
                                            'column_spacing' => '0',
                                            'responsive_on_mobile' => false,
                                            'vertical_align' => 'top',
                                            'padding'      => [
                                                'top'    => '15',
                                                'right'  => '0',
                                                'bottom' => '15',
                                                'left'   => '0',
                                            ],
                                            'border'       => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'border_radius' => [
                                                'top_left' => '0',
                                                'top_right' => '0',
                                                'bottom_left' => '0',
                                                'bottom_right' => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'background_image' => [
                                                'url'      => '',
                                                'position' => 'default',
                                                'x_position' => 0,
                                                'y_position' => 0,
                                                'repeat'   => 'default',
                                                'size'     => 'default',
                                            ],
                                            'inner_border_radius' => [
                                                'top_left' => 10,
                                                'top_right' => 10,
                                                'bottom_left' => 10,
                                                'bottom_right' => 10,
                                            ],
                                            'inner_background_color' => '#ffffff00',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'column_width'           => [],
                    'column_spacing'         => 20,
                    'responsive_on_mobile'   => false,
                    'vertical_align'         => 'top',
                    'padding'                => [
                        'top'    => 0,
                        'right'  => 30,
                        'bottom' => 20,
                        'left'   => 30,
                    ],
                    'border'                 => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'          => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'background_color'       => '#fff',
                    'background_image'       => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                    'inner_border_radius'    => [
                        'top_left'     => 0,
                        'top_right'    => 0,
                        'bottom_left'  => 0,
                        'bottom_right' => 0,
                    ],
                    'inner_background_color' => '#ffffff00',
                ]
            ),
            Divider::get_object_data(
                [
                    'align'            => 'center',
                    'padding'          => [
                        'top'    => 10,
                        'right'  => 30,
                        'bottom' => 10,
                        'left'   => 30,
                    ],
                    'width'            => '100',
                    'height'           => 4,
                    'background_color' => '#fff',
                    'divider_color'    => '#1a1a1a',
                    'divider_type'     => 'solid',
                ]
            ),
            Footer::get_object_data(
                [
                    'padding'          => [
                        'top'    => 20,
                        'right'  => '50',
                        'bottom' => '24',
                        'left'   => '50',
                    ],
                    'background_color' => '#ffffff',
                    'text_color'       => '#1a1a1a',
                    'font_family'      => '"Outfit", "DM Sans", sans-serif',
                    'rich_text'        => '<p style="text-align: center"><span style="font-size: 16px">This is an automated notification from [yaymail_site_name].</span></p>
                        <p style="text-align: center"><span style="font-size: 16px">Manage this order directly from your WooCommerce dashboard.</span></p>
                        <br>
                        <p style="text-align: center"><span style="font-size: 12px">© 2026 [yaymail_site_name]</span></p>',
                ]
            ),
        ];
    }
}
