<?php

namespace YayMail\TemplateLibrary\Templates\Processing;

use YayMail\Abstracts\BaseTemplate;
use YayMail\Elements\BillingAddress;
use YayMail\Elements\Button;
use YayMail\Elements\Column;
use YayMail\Elements\ColumnLayout;
use YayMail\Elements\Divider;
use YayMail\Elements\FeaturedProducts;
use YayMail\Elements\Heading;
use YayMail\Elements\Image;
use YayMail\Elements\Logo;
use YayMail\Elements\OrderDetails;
use YayMail\Elements\ShippingAddress;
use YayMail\Elements\SocialIcon;
use YayMail\Elements\Text;
use YayMail\Utils\SingletonTrait;

/**
 * Digital Picks template for customer_processing_order email.
 * Generated by tools/yaymail-template-gen — review/tweak values as needed.
 */
class DigitalPicks extends BaseTemplate {
    use SingletonTrait;

    public function __construct() {
        parent::__construct();
        $this->id                = 'processing_order_v14';
        $this->email_type        = 'customer_processing_order';
        $this->name              = 'Digital Picks';
        $this->description       = 'Showcase recommended tech products.';
        $this->categories        = [ 'Electronics' ];
        $this->template_settings = [
            'text_link_color' => '#000000',
        ];
        $this->access            = 'free';
        $this->elements          = [
            ColumnLayout::get_object_data(
                4,
                [
                    'children'               => [
                        Column::get_object_data(
                            29,
                            [
                                'children' => [
                                    Logo::get_object_data(
                                        [
                                            'padding' => [
                                                'top'    => '10',
                                                'right'  => '10',
                                                'bottom' => '10',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'src'     => 'https://images.wpbrandy.com/uploads/woo-black-logo.png',
                                            'align'   => 'left',
                                            'width'   => '116',
                                            'url'     => '#',
                                            'alt'     => 'Store logo',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            34.49,
                            [
                                'children' => [
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '15',
                                                'right'  => '0',
                                                'bottom' => '15',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'border'      => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'font_family' => '"Outfit", "DM Sans", sans-serif',
                                            'text_color'  => '#1a1a1a',
                                            'rich_text'   => '<p style="text-align: right"><span style="font-size: 16px">My Account</span></p>',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            27.76,
                            [
                                'children' => [
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '15',
                                                'right'  => '0',
                                                'bottom' => '15',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'border'      => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'font_family' => '"Outfit", "DM Sans", sans-serif',
                                            'text_color'  => '#1a1a1a',
                                            'rich_text'   => '<p style="text-align: center"><span style="font-size: 16px">Order Tracking</span></p>',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            8.75,
                            [
                                'children' => [
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '15',
                                                'right'  => '2',
                                                'bottom' => '15',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'border'      => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'font_family' => '"Outfit", "DM Sans", sans-serif',
                                            'text_color'  => '#1a1a1a',
                                            'rich_text'   => '<p style="text-align: right"><span style="font-size: 16px">Contact</span></p>',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'column_width'           => [],
                    'column_spacing'         => '0',
                    'responsive_on_mobile'   => false,
                    'vertical_align'         => 'top',
                    'padding'                => [
                        'top'    => '15',
                        'right'  => 20,
                        'bottom' => '15',
                        'left'   => 20,
                    ],
                    'border'                 => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'          => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'background_color'       => '#ffffff',
                    'background_image'       => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                    'inner_border_radius'    => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'inner_background_color' => '#ffffff00',
                ]
            ),
            ColumnLayout::get_object_data(
                1,
                [
                    'children'         => [
                        Column::get_object_data(
                            100,
                            [
                                'children' => [
                                    ColumnLayout::get_object_data(
                                        1,
                                        [
                                'children'               => [
                                    Column::get_object_data(
                                        100,
                                        [
                                            'children' => [
                                                Heading::get_object_data(
                                                    [
                                                        'padding' => [
                                                            'top'  => '0',
                                                            'right' => '0',
                                                            'bottom' => '12',
                                                            'left' => '0',
                                                        ],
                                                        'background_color' => '#ffffff00',
                                                        'border'  => [
                                                            'side' => 'none',
                                                            'width' => '1',
                                                            'style' => 'solid',
                                                            'color' => '#e5e5e5',
                                                            'custom' => [
                                                                'top'  => '1',
                                                                'right' => '1',
                                                                'bottom' => '1',
                                                                'left' => '1',
                                                            ],
                                                        ],
                                                        'font_family' => '"Outfit", "DM Sans", sans-serif',
                                                        'text_color' => '#1a1a1a',
                                                        'rich_text' => '<h1 style="font-size:30px;font-weight:300;line-height:normal;margin:0px;color:inherit"><h1 style="font-weight: bold;line-height: 1.15 !important;margin: 0"><span style="font-size: 36px;font-weight: bold">Thanks for Your Order!</span></h1></h1>',
                                                    ]
                                                ),
                                                Text::get_object_data(
                                                    [
                                                        'padding' => [
                                                            'top'  => '0',
                                                            'right' => '0',
                                                            'bottom' => '0',
                                                            'left' => '0',
                                                        ],
                                                        'background_color' => '#ffffff00',
                                                        'border'  => [
                                                            'side' => 'none',
                                                            'width' => '1',
                                                            'style' => 'solid',
                                                            'color' => '#e5e5e5',
                                                            'custom' => [
                                                                'top'  => '1',
                                                                'right' => '1',
                                                                'bottom' => '1',
                                                                'left' => '1',
                                                            ],
                                                        ],
                                                        'font_family' => '"Outfit", "DM Sans", sans-serif',
                                                        'text_color' => '#1a1a1a',
                                                        'rich_text' => '<p><span style="font-size: 14px;font-weight: 400">Order #[yaymail_order_id is_plain="true"]  •  Placed on [yaymail_order_date]</span></p>
                                                            <p><span style="font-size: 14px;font-weight: 400">Status: Processing</span></p>',
                                                    ]
                                                ),
                                            ],
                                            'border'   => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                        ]
                                    ),
                                ],
                                'column_width'           => [],
                                'column_spacing'         => '0',
                                'responsive_on_mobile'   => false,
                                'vertical_align'         => 'middle',
                                'padding'                => [
                                    'top'    => '40',
                                    'right'  => '50',
                                    'bottom' => '40',
                                    'left'   => 20,
                                ],
                                'border'                 => [
                                    'side'   => 'all',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#000000',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                                'border_radius'          => [
                                    'top_left'     => 10,
                                    'top_right'    => 10,
                                    'bottom_left'  => 10,
                                    'bottom_right' => 10,
                                ],
                                'background_color'       => '#DFFD90',
                                'background_image'       => [
                                    'url'        => 'https://images.wpbrandy.com/uploads/digitalpicks-background-1.png',
                                    'position'   => 'center_center',
                                    'x_position' => 0,
                                    'y_position' => 0,
                                    'repeat'     => 'no-repeat',
                                    'size'       => 'cover',
                                ],
                                'inner_border_radius'    => [
                                    'top_left'     => '0',
                                    'top_right'    => '0',
                                    'bottom_left'  => '0',
                                    'bottom_right' => '0',
                                ],
                                'inner_background_color' => '#ffffff00',
                                        ]
                                    ),
                                ],
                            ]
                        ),
                    ],
                    'padding'          => [
                        'top'    => 0,
                        'right'  => 20,
                        'bottom' => 0,
                        'left'   => 20,
                    ],
                    'background_color' => '#fff',
                    'background_image' => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                ]
            ),
            Text::get_object_data(
                [
                    'padding'          => [
                        'top'    => '24',
                        'right'  => 40,
                        'bottom' => 0,
                        'left'   => 40,
                    ],
                    'background_color' => '#ffffff',
                    'border'           => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'font_family'      => '"Outfit", "DM Sans", sans-serif',
                    'text_color'       => '#1a1a1a',
                    'rich_text'        => '<p><span style="font-size: 18px">Hi <strong>[yaymail_billing_first_name]</strong>,</span></p>',
                ]
            ),
            Text::get_object_data(
                [
                    'padding'          => [
                        'top'    => 0,
                        'right'  => 40,
                        'bottom' => '8',
                        'left'   => 40,
                    ],
                    'background_color' => '#ffffff',
                    'border'           => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'font_family'      => '"Outfit", "DM Sans", sans-serif',
                    'text_color'       => '#1a1a1a',
                    'rich_text'        => '<p><span style="font-size: 16px">Thank you for shopping with [yaymail_site_name]!</span></p>
<p><span style="white-space: pre-wrap;font-size: 16px">We’ve received your order and are getting it ready. You can review your order details below or track its progress anytime.</span></p>',
                ]
            ),
            ColumnLayout::get_object_data(
                2,
                [
                    'children'               => [
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    Button::get_object_data(
                                        [
                                            'padding'      => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => '0',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff',
                                            'button_type'  => 'default',
                                            'align'        => 'center',
                                            'width'        => '100%',
                                            'custom_width' => '50',
                                            'height'       => '21',
                                            'button_padding' => [
                                                'top'    => '12',
                                                'right'  => '20',
                                                'bottom' => '12',
                                                'left'   => '20',
                                            ],
                                            'button_background_color' => '#c0ff7c',
                                            'text_color'   => '#1a1a1a',
                                            'border'       => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'border_radius' => [
                                                'top_left' => 100,
                                                'top_right' => 100,
                                                'bottom_right' => 100,
                                                'bottom_left' => 100,
                                            ],
                                            'text'         => 'View Order',
                                            'url'          => '[yaymail_order_url]',
                                            'font_size'    => '16',
                                            'weight'       => '600',
                                            'font_family'  => '"Outfit", "DM Sans", sans-serif',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    Button::get_object_data(
                                        [
                                            'padding'      => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => '0',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff',
                                            'button_type'  => 'default',
                                            'align'        => 'center',
                                            'width'        => '100%',
                                            'custom_width' => '50',
                                            'height'       => '21',
                                            'button_padding' => [
                                                'top'    => '12',
                                                'right'  => '20',
                                                'bottom' => '12',
                                                'left'   => '20',
                                            ],
                                            'button_background_color' => '#ffffff',
                                            'text_color'   => '#000000',
                                            'border'       => [
                                                'side'  => 'all',
                                                'width' => '1',
                                                'style' => 'solid',
                                                'color' => '#000000',
                                            ],
                                            'border_radius' => [
                                                'top_left' => 100,
                                                'top_right' => 100,
                                                'bottom_right' => 100,
                                                'bottom_left' => 100,
                                            ],
                                            'text'         => 'Contact Support',
                                            'url'          => '[yaymail_site_url]',
                                            'font_size'    => '16',
                                            'weight'       => '600',
                                            'font_family'  => '"Outfit", "DM Sans", sans-serif',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'column_width'           => [],
                    'column_spacing'         => '12',
                    'responsive_on_mobile'   => false,
                    'vertical_align'         => 'top',
                    'padding'                => [
                        'top'    => '16',
                        'right'  => 40,
                        'bottom' => '16',
                        'left'   => 40,
                    ],
                    'border'                 => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'          => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'background_color'       => '#ffffff',
                    'background_image'       => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                    'inner_border_radius'    => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'inner_background_color' => '#ffffff00',
                ]
            ),
            ColumnLayout::get_object_data(
                1,
                [
                    'children'               => [
                        Column::get_object_data(
                            100,
                            [
                                'children' => [
                                    OrderDetails::get_object_data(
                                        [
                                            'rich_text'    => '[yaymail_order_details]',
                                            'payment_instructions' => '[yaymail_payment_instructions]',
                                            'padding'      => [
                                                'top'    => '15',
                                                'right'  => 40,
                                                'bottom' => '15',
                                                'left'   => 40,
                                            ],
                                            'background_color' => '#fafafa',
                                            'border'       => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'layout_type'  => 'modern',
                                            'title'        => '<p><span style="font-size: 24px;font-weight: 600">Order Summary</span></p>',
                                            'title_color'  => '#3d2d21',
                                            'text_color'   => '#3d2d21',
                                            'border_color' => '#e4e4e766',
                                            'font_family'  => '"Outfit", "DM Sans", sans-serif',
                                            'table_content_font_size' => 14,
                                            'table_heading_font_size' => 16,
                                            'show_table_header' => true,
                                            'product_title' => 'Product',
                                            'cost_title'   => 'Cost',
                                            'quantity_title' => 'Quantity',
                                            'price_title'  => 'Price',
                                            'cart_subtotal_title' => 'Subtotal:',
                                            'payment_method_title' => 'Payment method:',
                                            'order_total_title' => 'Total:',
                                            'order_note_title' => 'Note:',
                                            'shipping_title' => 'Shipping: [yaymail_shipping_method]',
                                            'discount_title' => 'Discount:',
                                            'custom_footer_rows' => [],
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'column_width'           => [],
                    'column_spacing'         => '0',
                    'responsive_on_mobile'   => false,
                    'vertical_align'         => 'top',
                    'padding'                => [
                        'top'    => '15',
                        'right'  => 40,
                        'bottom' => 5,
                        'left'   => 40,
                    ],
                    'border'                 => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'          => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'background_color'       => '#fff',
                    'background_image'       => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                    'inner_border_radius'    => [
                        'top_left'     => 10,
                        'top_right'    => 10,
                        'bottom_left'  => 10,
                        'bottom_right' => 10,
                    ],
                    'inner_background_color' => '#ffffff00',
                ]
            ),
            ColumnLayout::get_object_data(
                2,
                [
                    'children'               => [
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    ColumnLayout::get_object_data(
                                        1,
                                        [
                                            'children'     => [
                                                Column::get_object_data(
                                                    100,
                                                    [
                                                        'children' => [
                                                            ShippingAddress::get_object_data(
                                                                [
                                                                    'padding' => [
                                                                        'top'  => '15',
                                                                        'right' => '20',
                                                                        'bottom' => '15',
                                                                        'left' => '20',
                                                                    ],
                                                                    'background_color' => '#fafafa',
                                                                    'layout_type' => 'modern',
                                                                    'title_color' => '#1a1a1a',
                                                                    'text_color' => '#636363',
                                                                    'border_color' => '#e5e5e5',
                                                                    'font_family' => '"Outfit", "DM Sans", sans-serif',
                                                                    'title'   => '<p><span style="font-size: 18px;font-weight: 600">Shipping Address</span></p>',
                                                                    'shipping_content_font_size' => 14,
                                                                    'shipping_content_alignment' => 'left',
                                                                    'shipping_content_text_format' => [
                                                                        'bold' => false,
                                                                        'italic' => false,
                                                                        'underline' => false,
                                                                    ],
                                                                    'rich_text' => '[yaymail_shipping_address]',
                                                                ]
                                                            ),
                                                        ],
                                                        'border'   => [
                                                            'side' => 'none',
                                                            'width' => '1',
                                                            'style' => 'solid',
                                                            'color' => '#e5e5e5',
                                                            'custom' => [
                                                                'top'  => '1',
                                                                'right' => '1',
                                                                'bottom' => '1',
                                                                'left' => '1',
                                                            ],
                                                        ],
                                                    ]
                                                ),
                                            ],
                                            'column_width' => [],
                                            'column_spacing' => '0',
                                            'responsive_on_mobile' => false,
                                            'vertical_align' => 'top',
                                            'padding'      => [
                                                'top'    => '15',
                                                'right'  => '0',
                                                'bottom' => '15',
                                                'left'   => '0',
                                            ],
                                            'border'       => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'border_radius' => [
                                                'top_left' => 0,
                                                'top_right' => 0,
                                                'bottom_left' => 0,
                                                'bottom_right' => 0,
                                            ],
                                            'background_color' => '#fff',
                                            'background_image' => [
                                                'url'      => '',
                                                'position' => 'default',
                                                'x_position' => 0,
                                                'y_position' => 0,
                                                'repeat'   => 'default',
                                                'size'     => 'default',
                                            ],
                                            'inner_border_radius' => [
                                                'top_left' => 10,
                                                'top_right' => 10,
                                                'bottom_left' => 10,
                                                'bottom_right' => 10,
                                            ],
                                            'inner_background_color' => '#ffffff00',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    ColumnLayout::get_object_data(
                                        1,
                                        [
                                            'children'     => [
                                                Column::get_object_data(
                                                    100,
                                                    [
                                                        'children' => [
                                                            BillingAddress::get_object_data(
                                                                [
                                                                    'padding' => [
                                                                        'top'  => '15',
                                                                        'right' => '20',
                                                                        'bottom' => '15',
                                                                        'left' => '20',
                                                                    ],
                                                                    'background_color' => '#fafafa',
                                                                    'layout_type' => 'modern',
                                                                    'title_color' => '#1a1a1a',
                                                                    'text_color' => '#636363',
                                                                    'border_color' => '#e5e5e5',
                                                                    'font_family' => '"Outfit", "DM Sans", sans-serif',
                                                                    'title'   => '<p><span style="font-size: 18px;font-weight: 600">Billing Address</span></p>',
                                                                    'billing_content_font_size' => '14',
                                                                    'billing_content_alignment' => 'left',
                                                                    'billing_content_text_format' => [
                                                                        'bold' => false,
                                                                        'italic' => false,
                                                                        'underline' => false,
                                                                    ],
                                                                    'rich_text' => '[yaymail_billing_address]',
                                                                ]
                                                            ),
                                                        ],
                                                        'border'   => [
                                                            'side' => 'none',
                                                            'width' => '1',
                                                            'style' => 'solid',
                                                            'color' => '#e5e5e5',
                                                            'custom' => [
                                                                'top'  => '1',
                                                                'right' => '1',
                                                                'bottom' => '1',
                                                                'left' => '1',
                                                            ],
                                                        ],
                                                    ]
                                                ),
                                            ],
                                            'column_width' => [],
                                            'column_spacing' => '0',
                                            'responsive_on_mobile' => false,
                                            'vertical_align' => 'top',
                                            'padding'      => [
                                                'top'    => '15',
                                                'right'  => '0',
                                                'bottom' => '15',
                                                'left'   => '0',
                                            ],
                                            'border'       => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'border_radius' => [
                                                'top_left' => 0,
                                                'top_right' => 0,
                                                'bottom_left' => 0,
                                                'bottom_right' => 0,
                                            ],
                                            'background_color' => '#fff',
                                            'background_image' => [
                                                'url'      => '',
                                                'position' => 'default',
                                                'x_position' => 0,
                                                'y_position' => 0,
                                                'repeat'   => 'default',
                                                'size'     => 'default',
                                            ],
                                            'inner_border_radius' => [
                                                'top_left' => 10,
                                                'top_right' => 10,
                                                'bottom_left' => 10,
                                                'bottom_right' => 10,
                                            ],
                                            'inner_background_color' => '#ffffff00',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'column_width'           => [],
                    'column_spacing'         => 20,
                    'responsive_on_mobile'   => false,
                    'vertical_align'         => 'top',
                    'padding'                => [
                        'top'    => 0,
                        'right'  => 40,
                        'bottom' => 5,
                        'left'   => 40,
                    ],
                    'border'                 => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'          => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'background_color'       => '#fff',
                    'background_image'       => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                    'inner_border_radius'    => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'inner_background_color' => '#ffffff00',
                ]
            ),
            Divider::get_object_data(
                [
                    'align'            => 'center',
                    'padding'          => [
                        'top'    => '15',
                        'right'  => '40',
                        'bottom' => '15',
                        'left'   => '40',
                    ],
                    'width'            => '100',
                    'height'           => 4,
                    'background_color' => '#ffffff',
                    'divider_color'    => '#1a1a1a',
                    'divider_type'     => 'solid',
                ]
            ),
            FeaturedProducts::get_object_data(
                [
                    'padding'                     => [
                        'top'    => '24',
                        'right'  => 40,
                        'bottom' => '24',
                        'left'   => 40,
                    ],
                    'background_color'            => '#ffffff',
                    'text_color'                  => '#1a1a1a',
                    'font_family'                 => '"Outfit", "DM Sans", sans-serif',
                    'showing_items'               => [
                        'top_content',
                        'product_image',
                        'product_name',
                        'product_price',
                        'buy_button',
                    ],
                    'top_content'                 => '<p style="text-align: center"><span style="font-size: 24px;font-weight: 700">You May Also Like</span></p><p style="text-align: center"><span style="font-size: 14px">Discover more products picked for you.</span></p>',
                    'sale_price_color'            => '#1a1a1a',
                    'regular_price_color'         => '#808080',
                    'buy_button_label'            => 'Shop Now',
                    'buy_button_background_color' => '#c0ff7c',
                    'buy_button_text_color'       => '#1a1a1a',
                    'products_per_row'            => '3',
                    'product_type'                => 'newest',
                    'categories'                  => [],
                    'tags'                        => [],
                    'products'                    => [],
                    'sorted_by'                   => 'none',
                    'number_of_products'          => 3,
                ]
            ),
            ColumnLayout::get_object_data(
                1,
                [
                    'children'         => [
                        Column::get_object_data(
                            100,
                            [
                                'children' => [
                                    ColumnLayout::get_object_data(
                                        1,
                                        [
                                'children'               => [
                                    Column::get_object_data(
                                        100,
                                        [
                                            'children' => [
                                                Text::get_object_data(
                                                    [
                                                        'padding' => [
                                                            'top'  => 0,
                                                            'right' => '50',
                                                            'bottom' => 20,
                                                            'left' => '50',
                                                        ],
                                                        'background_color' => '#ffffff00',
                                                        'border'  => [
                                                            'side' => 'none',
                                                            'width' => '1',
                                                            'style' => 'solid',
                                                            'color' => '#e5e5e5',
                                                            'custom' => [
                                                                'top'  => '1',
                                                                'right' => '1',
                                                                'bottom' => '1',
                                                                'left' => '1',
                                                            ],
                                                        ],
                                                        'font_family' => '"Outfit", "DM Sans", sans-serif',
                                                        'text_color' => '#1a1a1a',
                                                        'rich_text' => '<p style="text-align: center"><span style="font-size: 24px"><strong>New Arrivals: Watches</strong></span></p>
                                            <p style="text-align: center"><span style="font-size: 14px">Discover the latest watches designed to elevate your everyday style.</span></p>',
                                                    ]
                                                ),
                                                Image::get_object_data(
                                                    [
                                                        'padding' => [
                                                            'top'  => '15',
                                                            'right' => '50',
                                                            'bottom' => '15',
                                                            'left' => '50',
                                                        ],
                                                        'background_color' => '#ffffff00',
                                                        'src' => 'https://images.wpbrandy.com/uploads/digital-picks-bg-2.png',
                                                        'align' => 'center',
                                                        'full_width' => false,
                                                        'width' => 443,
                                                        'url' => '#',
                                                        'alt' => '',
                                                    ]
                                                ),
                                                Button::get_object_data(
                                                    [
                                                        'padding' => [
                                                            'top'  => 20,
                                                            'right' => 0,
                                                            'bottom' => 0,
                                                            'left' => 0,
                                                        ],
                                                        'background_color' => '#ffffff00',
                                                        'button_type' => 'default',
                                                        'align' => 'center',
                                                        'width' => '50%',
                                                        'custom_width' => '50',
                                                        'height' => '21',
                                                        'button_padding' => [
                                                            'top'  => '12',
                                                            'right' => '20',
                                                            'bottom' => '12',
                                                            'left' => '20',
                                                        ],
                                                        'button_background_color' => '#c0ff7c',
                                                        'text_color' => '#1a1a1a',
                                                        'border' => [
                                                            'side' => 'none',
                                                            'width' => '1',
                                                            'style' => 'solid',
                                                            'color' => '#e5e5e5',
                                                            'custom' => [
                                                                'top'  => '1',
                                                                'right' => '1',
                                                                'bottom' => '1',
                                                                'left' => '1',
                                                            ],
                                                        ],
                                                        'border_radius' => [
                                                            'top_left' => '30',
                                                            'top_right' => '30',
                                                            'bottom_right' => '30',
                                                            'bottom_left' => '30',
                                                        ],
                                                        'text' => 'Explore the Collection',
                                                        'url'  => function_exists( 'wc_get_page_permalink' ) ? wc_get_page_permalink( 'shop' ) : home_url( '/' ),
                                                        'font_size' => 14,
                                                        'weight' => '600',
                                                        'font_family' => '"Outfit", "DM Sans", sans-serif',
                                                    ]
                                                ),
                                            ],
                                            'border'   => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                        ]
                                    ),
                                ],
                                'column_width'           => [],
                                'column_spacing'         => '0',
                                'responsive_on_mobile'   => false,
                                'vertical_align'         => 'top',
                                'padding'                => [
                                    'top'    => 60,
                                    'right'  => 20,
                                    'bottom' => 60,
                                    'left'   => 20,
                                ],
                                'border'                 => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                                'border_radius'          => [
                                    'top_left'     => '0',
                                    'top_right'    => '0',
                                    'bottom_left'  => '0',
                                    'bottom_right' => '0',
                                ],
                                'background_color'       => '#fafafa',
                                'background_image'       => [
                                    'url'        => '',
                                    'position'   => 'default',
                                    'x_position' => 0,
                                    'y_position' => 0,
                                    'repeat'     => 'default',
                                    'size'       => 'default',
                                ],
                                'inner_border_radius'    => [
                                    'top_left'     => '0',
                                    'top_right'    => '0',
                                    'bottom_left'  => '0',
                                    'bottom_right' => '0',
                                ],
                                'inner_background_color' => '#ffffff00',
                                        ]
                                    ),
                                ],
                            ]
                        ),
                    ],
                    'padding'          => [
                        'top'    => 0,
                        'right'  => 20,
                        'bottom' => 0,
                        'left'   => 20,
                    ],
                    'background_color' => '#fff',
                    'background_image' => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                ]
            ),
            ColumnLayout::get_object_data(
                1,
                [
                    'children'         => [
                        Column::get_object_data(
                            100,
                            [
                                'children' => [
                                    ColumnLayout::get_object_data(
                                        1,
                                        [
                                'children'               => [
                                    Column::get_object_data(
                                        100,
                                        [
                                            'children' => [
                                                Text::get_object_data(
                                                    [
                                                        'padding' => [
                                                            'top'  => '0',
                                                            'right' => '0',
                                                            'bottom' => '0',
                                                            'left' => '0',
                                                        ],
                                                        'background_color' => '#ffffff00',
                                                        'border'  => [
                                                            'side' => 'none',
                                                            'width' => '1',
                                                            'style' => 'solid',
                                                            'color' => '#e5e5e5',
                                                            'custom' => [
                                                                'top'  => '1',
                                                                'right' => '1',
                                                                'bottom' => '1',
                                                                'left' => '1',
                                                            ],
                                                        ],
                                                        'font_family' => '"Outfit", "DM Sans", sans-serif',
                                                        'text_color' => '#ffffff',
                                                        'rich_text' => '<p style="text-align: center"><span style="font-size: 16px">For questions, contact <u>hi@yourwoostore.com</u>, visit our <u>FAQs</u>, or <u>chat</u> with us during operating hours for account support</span></p>',
                                                    ]
                                                ),
                                                SocialIcon::get_object_data(
                                                    [
                                                        'padding' => [
                                                            'top'  => '20',
                                                            'right' => '0',
                                                            'bottom' => '12',
                                                            'left' => '0',
                                                        ],
                                                        'background_color' => '#ffffff00',
                                                        'align'   => 'center',
                                                        'width_icon' => '32',
                                                        'spacing' => '12',
                                                        'theme'   => 'Colorful',
                                                        'icon_list' => [
                                                            [
                                                                'icon' => 'facebook',
                                                                'url'  => '#',
                                                            ],
                                                            [
                                                                'icon' => 'instagram',
                                                                'url'  => '#',
                                                            ],
                                                            [
                                                                'icon' => 'tiktok',
                                                                'url'  => '#',
                                                            ],
                                                            [
                                                                'icon' => 'youtube',
                                                                'url'  => '#',
                                                            ],
                                                        ],
                                                    ]
                                                ),
                                                Text::get_object_data(
                                                    [
                                                        'padding' => [
                                                            'top'  => '0',
                                                            'right' => '0',
                                                            'bottom' => 0,
                                                            'left' => '0',
                                                        ],
                                                        'background_color' => '#ffffff00',
                                                        'border'  => [
                                                            'side' => 'none',
                                                            'width' => '1',
                                                            'style' => 'solid',
                                                            'color' => '#e5e5e5',
                                                            'custom' => [
                                                                'top'  => '1',
                                                                'right' => '1',
                                                                'bottom' => '1',
                                                                'left' => '1',
                                                            ],
                                                        ],
                                                        'font_family' => '"Outfit", "DM Sans", sans-serif',
                                                        'text_color' => '#ffffff',
                                                        'rich_text' => '<p style="text-align: center"><span style="font-size: 12px">© 2026 [yaymail_site_name]. All rights reserved.</span></p>',
                                                    ]
                                                ),
                                            ],
                                            'border'   => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                        ]
                                    ),
                                ],
                                'column_width'           => [],
                                'column_spacing'         => '0',
                                'responsive_on_mobile'   => false,
                                'vertical_align'         => 'top',
                                'padding'                => [
                                    'top'    => 40,
                                    'right'  => 40,
                                    'bottom' => 40,
                                    'left'   => 40,
                                ],
                                'border'                 => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                                'border_radius'          => [
                                    'top_left'     => '0',
                                    'top_right'    => '0',
                                    'bottom_left'  => '0',
                                    'bottom_right' => '0',
                                ],
                                'background_color'       => '#1a1a1a',
                                'background_image'       => [
                                    'url'        => '',
                                    'position'   => 'default',
                                    'x_position' => 0,
                                    'y_position' => 0,
                                    'repeat'     => 'default',
                                    'size'       => 'default',
                                ],
                                'inner_border_radius'    => [
                                    'top_left'     => '0',
                                    'top_right'    => '0',
                                    'bottom_left'  => '0',
                                    'bottom_right' => '0',
                                ],
                                'inner_background_color' => '#ffffff00',
                                        ]
                                    ),
                                ],
                            ]
                        ),
                    ],
                    'padding'          => [
                        'top'    => 0,
                        'right'  => 20,
                        'bottom' => 20,
                        'left'   => 20,
                    ],
                    'background_color' => '#fff',
                    'background_image' => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                ]
            ),
        ];
    }
}
