<?php

namespace YayMail\TemplateLibrary\Templates\Processing;

use YayMail\Abstracts\BaseTemplate;
use YayMail\Elements\BillingAddress;
use YayMail\Elements\Button;
use YayMail\Elements\Column;
use YayMail\Elements\ColumnLayout;
use YayMail\Elements\Container;
use YayMail\Elements\FeaturedProducts;
use YayMail\Elements\Heading;
use YayMail\Elements\Logo;
use YayMail\Elements\OrderDetails;
use YayMail\Elements\OrderProgress;
use YayMail\Elements\ShippingAddress;
use YayMail\Elements\SocialIcon;
use YayMail\Elements\Text;
use YayMail\Utils\SingletonTrait;

/**
 * Fashion template for Processing Order email.
 * Generated by tools/yaymail-template-gen — review/tweak values as needed.
 */
class Fashion extends BaseTemplate {
    use SingletonTrait;

    public function __construct() {
        parent::__construct();
        $this->id                = 'processing_order_v9';
        $this->email_type        = 'customer_processing_order';
        $this->name              = 'Fashion';
        $this->description       = 'Fashion template for Processing Order email.';
        $this->template_settings = [
            'text_link_color' => '#1A1A1A',
        ];
        $this->modified_date     = '2026-07-21';
        $this->access            = 'free';
        $this->elements          = [
            ColumnLayout::get_object_data(
                4,
                [
                    'children'         => [
                        Column::get_object_data(
                            29,
                            [
                                'children' => [
                                    Logo::get_object_data(
                                        [
                                            'padding' => [
                                                'top'    => '10',
                                                'right'  => '10',
                                                'bottom' => '10',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#1A1A1A00',
                                            'src'     => 'https://images.wpbrandy.com/uploads/woo-green-logo-1.png',
                                            'align'   => 'left',
                                            'width'   => '117',
                                            'alt'     => 'Store logo',
                                        ]
                                    ),
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            34.49,
                            [
                                'children' => [
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '15',
                                                'right'  => '0',
                                                'bottom' => '15',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#1a1a1a',
                                            'font_family' => 'Georgia, serif',
                                            'text_color'  => '#ffffff',
                                            'rich_text'   => '<p style="text-align: right"><span style="font-size: 14px;font-weight: 400">My Account</span></p>',
                                        ]
                                    ),
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            27.76,
                            [
                                'children' => [
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '15',
                                                'right'  => '0',
                                                'bottom' => '15',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#1a1a1a',
                                            'font_family' => 'Georgia, serif',
                                            'text_color'  => '#ffffff',
                                            'rich_text'   => '<p style="text-align: center"><span style="font-size: 14px;font-weight: 400">Order Tracking</span></p>',
                                        ]
                                    ),
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            8.75,
                            [
                                'children' => [
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '15',
                                                'right'  => '2',
                                                'bottom' => '15',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#1a1a1a',
                                            'font_family' => 'Georgia, serif',
                                            'text_color'  => '#ffffff',
                                            'rich_text'   => '<p style="text-align: right"><span style="font-size: 14px;font-weight: 400">Support</span></p>',
                                        ]
                                    ),
                                ],
                            ]
                        ),
                    ],
                    'padding'          => [
                        'top'    => '15',
                        'right'  => 40,
                        'bottom' => '15',
                        'left'   => 40,
                    ],
                    'background_color' => '#1A1A1A',
                ]
            ),
            ColumnLayout::get_object_data(
                2,
                [
                    'children'         => [
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => '0',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#F3E8FF00',
                                            'font_family' => 'Georgia, serif',
                                            'text_color'  => '#1A1A1A',
                                            'rich_text'   => '<p style="text-align: left"><span style="font-size: 12px;font-weight: bold">ORDER NUMBER: #[yaymail_order_id is_plain="true"]</span></p>',
                                        ]
                                    ),
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => '0',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#F3E8FF00',
                                            'font_family' => 'Georgia, serif',
                                            'text_color'  => '#1A1A1A',
                                            'rich_text'   => '<p style="text-align: right"><span style="font-size: 12px;font-weight: bold">ORDER DATE: [yaymail_order_date]</span></p>',
                                        ]
                                    ),
                                ],
                            ]
                        ),
                    ],
                    'padding'          => [
                        'top'    => 15,
                        'right'  => 40,
                        'bottom' => 15,
                        'left'   => 40,
                    ],
                    'background_color' => '#FFFFFF',
                ]
            ),
            ColumnLayout::get_object_data(
                1,
                [
                    'children'         => [
                        Column::get_object_data(
                            100,
                            [
                                'children' => [
                                    Heading::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => 20,
                                                'right'  => 40,
                                                'bottom' => 35,
                                                'left'   => 40,
                                            ],
                                            'background_color' => '#F3E8FF00',
                                            'font_family' => 'Georgia, serif',
                                            'text_color'  => '#1A1A1A',
                                            'rich_text'   => '<p style="text-align: center"><span style="font-weight: bold;font-size: 56px; line-height: normal">Good news!</span><br><span style="font-weight: bold;font-size: 56px; line-height: normal">Your order is complete</span></p>',
                                        ]
                                    ),
                                ],
                            ]
                        ),
                    ],
                    'padding'          => [
                        'top'    => 0,
                        'right'  => '50',
                        'bottom' => 0,
                        'left'   => '50',
                    ],
                    'background_color' => '#ffffff',
                    'background_image' => [
                        'url'      => 'https://images.wpbrandy.com/uploads/processing-9-img-1.png',
                        'position' => 'default',
                        'size'     => 'cover',
                        'repeat'   => 'no-repeat',
                    ],
                ]
            ),
            Text::get_object_data(
                [
                    'padding'          => [
                        'top'    => '32',
                        'right'  => 40,
                        'bottom' => '8',
                        'left'   => 40,
                    ],
                    'background_color' => '#ffffff',
                    'font_family'      => 'Georgia, serif',
                    'text_color'       => '#333439',
                    'rich_text'        => '<p><span style="font-size: 18px;font-weight: 700">Hi [yaymail_billing_first_name] [yaymail_billing_last_name],</span></p><p><span style="font-size: 16px">Thanks for your order! Your order has been successfully received and is being processed.</span></p>',
                ]
            ),
            OrderProgress::get_object_data(
                [
                    'padding'                  => [
                        'top'    => 20,
                        'right'  => 60,
                        'bottom' => 20,
                        'left'   => 60,
                    ],
                    'display_style'            => 'filled_bar',
                    'connector_height'         => '2',
                    'connector_active_color'   => '#e9ecef',
                    'connector_inactive_color' => '#e9ecef',
                    'label_active_color'       => '#1A1A1A',
                    'icon_size'                => '24',
                    'label_font_size'          => '12',
                    'font_family'              => 'Georgia, serif',
                    'steps'                    => [
                        [
                            'title'             => 'Confirmed',
                            'image_url'         => 'https://images.wpbrandy.com/uploads/processing-9-icon-1.png',
                            'image_bg_color'    => '#9ca2d2',
                            'icon_border_color' => '#9ca2d2',
                            'icon_border_style' => 'solid',
                            'icon_border_width' => 2,
                        ],
                        [
                            'title'             => 'Processing',
                            'image_url'         => 'https://images.wpbrandy.com/uploads/processing-9-icon-2.png',
                            'image_bg_color'    => '#9ca2d2',
                            'icon_border_color' => '#9ca2d2',
                            'icon_border_style' => 'solid',
                            'icon_border_width' => 2,
                        ],
                        [
                            'title'             => 'Completed',
                            'image_url'         => 'https://images.wpbrandy.com/uploads/processing-9-icon-3.png',
                            'image_bg_color'    => '#9ca2d2',
                            'icon_border_color' => '#9ca2d2',
                            'icon_border_style' => 'solid',
                            'icon_border_width' => 2,
                        ],
                    ],
                ]
            ),
            ColumnLayout::get_object_data(
                1,
                [
                    'children' => [
                        Column::get_object_data(
                            100,
                            [
                                'children' => [
                                    OrderDetails::get_object_data(
                                        [
                                            'padding'      => [
                                                'top'    => 30,
                                                'right'  => '20',
                                                'bottom' => 10,
                                                'left'   => '20',
                                            ],
                                            'background_color' => '#ffffff',
                                            'border'       => [
                                                'side'  => 'all',
                                                'width' => '1',
                                                'style' => 'solid',
                                                'color' => '#e9ecef00',
                                            ],
                                            'layout_type'  => 'modern',
                                            'title'        => '<p style="text-align: center"><span style="font-size: 20px;font-weight: bold">Order details</span><br /><span style="font-size: 14px;font-weight: 400">Order confirmation number: <strong>#[yaymail_order_id is_plain="true"]</strong></span></p>',
                                            'title_color'  => '#1A1A1A',
                                            'text_color'   => '#333439',
                                            'border_color' => '#e9ecef',
                                            'font_family'  => 'Georgia, serif',
                                        ]
                                    ),
                                    Button::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => 10,
                                                'right'  => '20',
                                                'bottom' => 30,
                                                'left'   => '20',
                                            ],
                                            'background_color' => '#ffffff',
                                            'width'       => '100%',
                                            'button_background_color' => '#d5f381',
                                            'text_color'  => '#1A1A1A',
                                            'border'      => [
                                                'side'   => 'custom',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#1a1a1a',
                                                'custom' => [
                                                    'top'  => 1,
                                                    'right' => 3,
                                                    'bottom' => 3,
                                                    'left' => 1,
                                                ],
                                            ],
                                            'border_radius' => [
                                                'top_left' => 0,
                                                'top_right' => 0,
                                                'bottom_right' => 0,
                                                'bottom_left' => 0,
                                            ],
                                            'text'        => 'View Order Detail',
                                            'url'         => '[yaymail_order_url]',
                                            'font_size'   => '16',
                                            'weight'      => '700',
                                            'font_family' => 'Georgia, serif',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'all',
                                    'width'  => 10,
                                    'style'  => 'solid',
                                    'color'  => '#efeaff',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'padding'  => [
                        'top'    => 15,
                        'right'  => '40',
                        'bottom' => 30,
                        'left'   => '40',
                    ],
                ]
            ),
            ColumnLayout::get_object_data(
                2,
                [
                    'children'         => [
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    ShippingAddress::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '15',
                                                'right'  => 40,
                                                'bottom' => '15',
                                                'left'   => 40,
                                            ],
                                            'background_color' => '#efeaff',
                                            'layout_type' => 'modern',
                                            'title_color' => '#1a1a1a',
                                            'text_color'  => '#1a1a1a',
                                            'font_family' => 'Georgia, serif',
                                            'title'       => '<p style="text-align: center"><span style="font-size: 20px;font-weight: 600">Shipping Address</span></p>',
                                            'shipping_content_alignment' => 'center',
                                            'shipping_content_text_format' => [
                                                'bold'   => false,
                                                'italic' => false,
                                                'underline' => false,
                                            ],
                                        ]
                                    ),
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    BillingAddress::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '15',
                                                'right'  => 40,
                                                'bottom' => '15',
                                                'left'   => 40,
                                            ],
                                            'background_color' => '#efeaff',
                                            'layout_type' => 'modern',
                                            'title_color' => '#1a1a1a',
                                            'text_color'  => '#1a1a1a',
                                            'font_family' => 'Georgia, serif',
                                            'title'       => '<p style="text-align: center"><span style="font-size: 20px;font-weight: 600">Billing Address</span></p>',
                                            'billing_content_alignment' => 'center',
                                            'billing_content_text_format' => [
                                                'bold'   => false,
                                                'italic' => false,
                                                'underline' => false,
                                            ],
                                        ]
                                    ),
                                ],
                            ]
                        ),
                    ],
                    'background_color' => '#efeaff',
                ]
            ),
            ColumnLayout::get_object_data(
                1,
                [
                    'children'         => [
                        Column::get_object_data(
                            100,
                            [
                                'children' => [
                                    FeaturedProducts::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => 0,
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff',
                                            'text_color'  => '#333439',
                                            'font_family' => 'Georgia, serif',
                                            'showing_items' => [
                                                'product_image',
                                                'product_name',
                                                'product_price',
                                                'product_original_price',
                                                'top_content',
                                            ],
                                            'top_content' => '<p style="text-align: center;"><span style="font-size: 24px;"><strong>You might also like to try</strong></span></p>
                                                <p style="text-align: center;">Check out other products in our store you might like</p>
                                                <br>',
                                            'sale_price_color' => '#1A1A1A',
                                            'regular_price_color' => '#9CA3AF',
                                            'products_per_row' => 2,
                                            'number_of_products' => 4,
                                        ]
                                    ),
                                    Button::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => 30,
                                                'right'  => '0',
                                                'bottom' => 30,
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff',
                                            'button_background_color' => '#d5f381',
                                            'text_color'  => '#1A1A1A',
                                            'border'      => [
                                                'side'   => 'custom',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#1a1a1a',
                                                'custom' => [
                                                    'top'  => 1,
                                                    'right' => 3,
                                                    'bottom' => 3,
                                                    'left' => '1',
                                                ],
                                            ],
                                            'border_radius' => [
                                                'top_left' => 0,
                                                'top_right' => 0,
                                                'bottom_right' => 0,
                                                'bottom_left' => 0,
                                            ],
                                            'text'        => 'View all products',
                                            'font_size'   => '14',
                                            'weight'      => '700',
                                            'font_family' => 'Georgia, serif',
                                            'url'         => function_exists( 'wc_get_page_permalink' ) ? wc_get_page_permalink( 'shop' ) : home_url( '/' ),
                                        ]
                                    ),
                                ],
                            ]
                        ),
                    ],
                    'padding'          => [
                        'top'    => '40',
                        'right'  => 40,
                        'bottom' => 10,
                        'left'   => 40,
                    ],
                    'background_color' => '#ffffff',
                ]
            ),
            ColumnLayout::get_object_data(
                1,
                [
                    'children'         => [
                        Column::get_object_data(
                            100,
                            [
                                'children' => [
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => '0',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#1A1A1A',
                                            'font_family' => 'Georgia, serif',
                                            'text_color'  => '#ffffff',
                                            'rich_text'   => '<p style="text-align: center"><span style="font-size: 16px">For questions, contact us via our website, visit our <u>FAQs</u>, or <u>chat</u> with us during operating hours for instant support.</span></p>',
                                        ]
                                    ),
                                    SocialIcon::get_object_data(
                                        [
                                            'padding'    => [
                                                'top'    => '20',
                                                'right'  => '0',
                                                'bottom' => '16',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#1A1A1A',
                                            'width_icon' => '32',
                                            'spacing'    => '12',
                                            'icon_list'  => [
                                                [
                                                    'icon' => 'facebook',
                                                    'url'  => '#',
                                                ],
                                                [
                                                    'icon' => 'instagram',
                                                    'url'  => '#',
                                                ],
                                                [
                                                    'icon' => 'tiktok',
                                                    'url'  => '#',
                                                ],
                                                [
                                                    'icon' => 'youtube',
                                                    'url'  => '#',
                                                ],
                                            ],
                                        ]
                                    ),
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => '0',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#1A1A1A',
                                            'font_family' => 'Georgia, serif',
                                            'text_color'  => '#ffffff',
                                            'rich_text'   => '<p style="text-align: center"><span style="font-size: 12px">© 2024 WooCommerce</span></p>',
                                        ]
                                    ),
                                ],
                            ]
                        ),
                    ],
                    'padding'          => [
                        'top'    => '32',
                        'right'  => 40,
                        'bottom' => '32',
                        'left'   => 40,
                    ],
                    'background_color' => '#1A1A1A',
                ]
            ),
        ];
    }
}
