<?php

namespace YayMail\TemplateLibrary\Templates\Processing;

use YayMail\Abstracts\BaseTemplate;
use YayMail\Elements\Button;
use YayMail\Elements\Column;
use YayMail\Elements\ColumnLayout;
use YayMail\Elements\FeaturedProducts;
use YayMail\Elements\Heading;
use YayMail\Elements\Image;
use YayMail\Elements\Logo;
use YayMail\Elements\SocialIcon;
use YayMail\Elements\Text;
use YayMail\Utils\SingletonTrait;

/**
 * Processing 10 template for customer_processing_order email.
 * Generated by tools/yaymail-template-gen — review/tweak values as needed.
 */
// class Processing10 extends BaseTemplate {
// use SingletonTrait;

// public function __construct() {
// parent::__construct();
// $this->id          = 'processing_order_v10';
// $this->email_type  = 'customer_processing_order';
// $this->name        = 'Processing 10';
// $this->description = 'Dark flash sale hero with lavender product grid and new arrivals gallery';
// $this->access      = 'free';
// $this->elements    = [
// ColumnLayout::get_object_data(
// 4,
// [
// 'children'         => [
// Column::get_object_data(
// 29,
// [
// 'children' => [
// Logo::get_object_data(
// [
// 'padding' => [
// 'top'    => '10',
// 'right'  => '10',
// 'bottom' => '10',
// 'left'   => '0',
// ],
// 'background_color' => '#080808',
// 'src'     => 'https://images.wpbrandy.com/uploads/woo-green-logo-1.png',
// 'align'   => 'left',
// 'width'   => 94,
// 'alt'     => 'Store logo',
// ]
// ),
// ],
// ]
// ),
// Column::get_object_data(
// 34.49,
// [
// 'children' => [
// Text::get_object_data(
// [
// 'padding'     => [
// 'top'    => '15',
// 'right'  => '0',
// 'bottom' => '15',
// 'left'   => '0',
// ],
// 'background_color' => '#080808',
// 'font_family' => 'Tahoma, Geneva, sans-serif',
// 'text_color'  => '#ffffff',
// 'rich_text'   => '<p style="text-align: right"><span style="font-size: 14px">My Account</span></p>',
// ]
// ),
// ],
// ]
// ),
// Column::get_object_data(
// 27.76,
// [
// 'children' => [
// Text::get_object_data(
// [
// 'padding'     => [
// 'top'    => '15',
// 'right'  => '0',
// 'bottom' => '15',
// 'left'   => '0',
// ],
// 'background_color' => '#080808',
// 'font_family' => 'Tahoma, Geneva, sans-serif',
// 'text_color'  => '#ffffff',
// 'rich_text'   => '<p style="text-align: center"><span style="font-size: 14px">Order Tracking</span></p>',
// ]
// ),
// ],
// ]
// ),
// Column::get_object_data(
// 8.75,
// [
// 'children' => [
// Text::get_object_data(
// [
// 'padding'     => [
// 'top'    => '15',
// 'right'  => '2',
// 'bottom' => '15',
// 'left'   => '0',
// ],
// 'background_color' => '#080808',
// 'font_family' => 'Tahoma, Geneva, sans-serif',
// 'text_color'  => '#ffffff',
// 'rich_text'   => '<p style="text-align: right"><span style="font-size: 14px">Contact</span></p>',
// ]
// ),
// ],
// ]
// ),
// ],
// 'padding'          => [
// 'top'    => '20',
// 'right'  => '50',
// 'bottom' => '20',
// 'left'   => '50',
// ],
// 'background_color' => '#080808',
// ]
// ),
// ColumnLayout::get_object_data(
// 1,
// [
// 'children'         => [
// Column::get_object_data(
// 100,
// [
// 'children' => [
// Heading::get_object_data(
// [
// 'padding'     => [
// 'top'    => '0',
// 'right'  => '0',
// 'bottom' => '16',
// 'left'   => '0',
// ],
// 'background_color' => '#08080800',
// 'font_family' => 'Tahoma, Geneva, sans-serif',
// 'rich_text'   => '<h1 style="font-size: 56px;font-weight: 800;color: #ffffff;margin: 0px;line-height: 1 !important;text-align: left"><span style="font-size: 96px">FLASH⚡</span></h1>',
// ]
// ),
// Heading::get_object_data(
// [
// 'padding'     => [
// 'top'    => '0',
// 'right'  => '0',
// 'bottom' => '16',
// 'left'   => '0',
// ],
// 'background_color' => '#08080800',
// 'font_family' => 'Tahoma, Geneva, sans-serif',
// 'rich_text'   => '<h1 style="font-size: 56px;font-weight: 800;color: #ffffff;margin: 0px;line-height: 1 !important;text-align: left"><span style="font-size: 120px">FRIDAY</span></h1>',
// ]
// ),
// Text::get_object_data(
// [
// 'padding'     => [
// 'top'    => '0',
// 'right'  => '0',
// 'bottom' => 0,
// 'left'   => '0',
// ],
// 'background_color' => '#1a1a1a',
// 'font_family' => 'Tahoma, Geneva, sans-serif',
// 'text_color'  => '#ffffff',
// 'rich_text'   => '<p style="text-align: left"><span style="font-size: 20px;font-weight: 400">UP TO 70% OFF - BEST FASHION COLLECTION</span></p>',
// ]
// ),
// Text::get_object_data(
// [
// 'padding'     => [
// 'top'    => 15,
// 'right'  => '0',
// 'bottom' => 20,
// 'left'   => '0',
// ],
// 'background_color' => '#1a1a1a',
// 'font_family' => 'Tahoma, Geneva, sans-serif',
// 'text_color'  => '#ffffff',
// 'rich_text'   => '<p style="text-align: left"><span style="font-size: 16px">Promotion 12 May - 1 Jun</span></p>',
// ]
// ),
// ],
// ]
// ),
// ],
// 'padding'          => [
// 'top'    => 35,
// 'right'  => '50',
// 'bottom' => '0',
// 'left'   => '50',
// ],
// 'background_color' => '#1A1A1A',
// ]
// ),
// ColumnLayout::get_object_data(
// 2,
// [
// 'children'         => [
// Column::get_object_data(
// 50,
// [
// 'children' => [
// Image::get_object_data(
// [
// 'padding'    => [
// 'top'    => '0',
// 'right'  => '0',
// 'bottom' => '0',
// 'left'   => '0',
// ],
// 'background_color' => '#1A1A1A00',
// 'src'        => 'https://images.wpbrandy.com/uploads/processing-10-img-1.png',
// 'full_width' => true,
// 'alt'        => 'Fashion model trench coat',
// ]
// ),
// ],
// ]
// ),
// Column::get_object_data(
// 50,
// [
// 'children' => [
// Image::get_object_data(
// [
// 'padding'    => [
// 'top'    => '0',
// 'right'  => '0',
// 'bottom' => '0',
// 'left'   => '0',
// ],
// 'background_color' => '#1A1A1A00',
// 'src'        => 'https://images.wpbrandy.com/uploads/processing-10-img-2.png',
// 'full_width' => true,
// 'alt'        => 'Fashion model puffer jacket',
// ]
// ),
// ],
// ]
// ),
// ],
// 'column_spacing'   => 0,
// 'padding'          => [
// 'top'    => 2,
// 'right'  => 0,
// 'bottom' => 2,
// 'left'   => 0,
// ],
// 'background_color' => '#1A1A1A',
// ]
// ),
// Text::get_object_data(
// [
// 'padding'          => [
// 'top'    => 25,
// 'right'  => '50',
// 'bottom' => 25,
// 'left'   => '50',
// ],
// 'background_color' => '#1A1A1A',
// 'font_family'      => 'Tahoma, Geneva, sans-serif',
// 'text_color'       => '#ffffff',
// 'rich_text'        => '<p style="text-align: center"><span style="font-size: 30px;font-weight: 400">2026 SPRING / SUMMER COLLECTION</span></p>',
// ]
// ),
// ColumnLayout::get_object_data(
// 1,
// [
// 'children'         => [
// Column::get_object_data(
// 100,
// [
// 'children' => [
// FeaturedProducts::get_object_data(
// [
// 'padding'      => [
// 'top'    => '0',
// 'right'  => '0',
// 'bottom' => '24',
// 'left'   => '0',
// ],
// 'background_color' => '#868ed4',
// 'text_color'   => '#ffffff',
// 'font_family'  => 'Tahoma, Geneva, sans-serif',
// 'showing_items' => [
// 'product_image',
// 'product_name',
// 'product_price',
// 'product_original_price',
// 'top_content',
// ],
// 'top_content'  => '<p style="text-align: center;"><span style="font-size: 30px;"><strong>You might also like to try</strong></span></p>
// <p style="text-align: center;">Check out other products in our store that you might like</p>
// <br>',
// 'sale_price_color' => '#ffffff',
// 'regular_price_color' => '#E0E0E0',
// 'products_per_row' => '2',
// 'product_type' => 'on_sale',
// 'number_of_products' => 4,
// ]
// ),
// Button::get_object_data(
// [
// 'padding'     => [
// 'top'    => '0',
// 'right'  => '0',
// 'bottom' => '0',
// 'left'   => '0',
// ],
// 'background_color' => '#929AD300',
// 'button_background_color' => '#d5f381',
// 'text_color'  => '#1A1A1A',
// 'border'      => [
// 'side'   => 'custom',
// 'width'  => '1',
// 'style'  => 'solid',
// 'color'  => '#000000',
// 'custom' => [
// 'top'  => '1',
// 'right' => 3,
// 'bottom' => 3,
// 'left' => '1',
// ],
// ],
// 'border_radius' => [
// 'top_left' => '0',
// 'top_right' => '0',
// 'bottom_right' => 0,
// 'bottom_left' => '0',
// ],
// 'text'        => 'View all products',
// 'font_size'   => '14',
// 'weight'      => '700',
// 'font_family' => 'Tahoma, Geneva, sans-serif',
// ]
// ),
// ],
// ]
// ),
// ],
// 'padding'          => [
// 'top'    => '40',
// 'right'  => '50',
// 'bottom' => '40',
// 'left'   => '50',
// ],
// 'background_color' => '#868ed4',
// ]
// ),
// ColumnLayout::get_object_data(
// 1,
// [
// 'children'         => [
// Column::get_object_data(
// 100,
// [
// 'children' => [
// FeaturedProducts::get_object_data(
// [
// 'padding'     => [
// 'top'    => '15',
// 'right'  => 0,
// 'bottom' => '15',
// 'left'   => 0,
// ],
// 'background_color' => '#1a1a1a',
// 'text_color'  => '#ffffff',
// 'font_family' => 'Tahoma, Geneva, sans-serif',
// 'showing_items' => [
// 'top_content',
// 'product_image',
// ],
// 'top_content' => '<p style="text-align: center;"><span style="font-weight: bold;">The best of</span></p>
// <p style="text-align: center;"><span style="font-size: 30px; font-weight: bold;"><strong style="text-align: center;">New arrivals</strong></span></p>
// </br>',
// 'products_per_row' => 6,
// 'number_of_products' => 6,
// ]
// ),
// ],
// ]
// ),
// ],
// 'column_spacing'   => 0,
// 'padding'          => [
// 'top'    => 25,
// 'right'  => '50',
// 'bottom' => 25,
// 'left'   => '50',
// ],
// 'background_color' => '#1A1A1A',
// ]
// ),
// ColumnLayout::get_object_data(
// 1,
// [
// 'children'         => [
// Column::get_object_data(
// 100,
// [
// 'children' => [
// Text::get_object_data(
// [
// 'padding'     => [
// 'top'    => '0',
// 'right'  => '0',
// 'bottom' => '0',
// 'left'   => '0',
// ],
// 'background_color' => '#929AD3',
// 'font_family' => 'Tahoma, Geneva, sans-serif',
// 'text_color'  => '#ffffff',
// 'rich_text'   => '<p style="text-align: center"><span style="font-size: 16px">For questions, contact hi@yourwoostore.com, visit our <u>FAQs</u>, or <u>chat</u> with us during operating hours for account support</span></p>',
// ]
// ),
// SocialIcon::get_object_data(
// [
// 'padding'    => [
// 'top'    => '20',
// 'right'  => '0',
// 'bottom' => '16',
// 'left'   => '0',
// ],
// 'background_color' => '#929AD3',
// 'width_icon' => '32',
// 'spacing'    => '12',
// 'icon_list'  => [
// [
// 'icon' => 'facebook',
// 'url'  => '#',
// ],
// [
// 'icon' => 'instagram',
// 'url'  => '#',
// ],
// [
// 'icon' => 'tiktok',
// 'url'  => '#',
// ],
// [
// 'icon' => 'youtube',
// 'url'  => '#',
// ],
// ],
// ]
// ),
// Text::get_object_data(
// [
// 'padding'     => [
// 'top'    => '0',
// 'right'  => '0',
// 'bottom' => '0',
// 'left'   => '0',
// ],
// 'background_color' => '#929AD3',
// 'font_family' => 'Tahoma, Geneva, sans-serif',
// 'text_color'  => '#ffffff',
// 'rich_text'   => '<p style="text-align: center"><span style="font-size: 12px;font-weight: 400">© 2026 WooCommerce</span></p>',
// ]
// ),
// ],
// ]
// ),
// ],
// 'padding'          => [
// 'top'    => '32',
// 'right'  => '50',
// 'bottom' => '32',
// 'left'   => '50',
// ],
// 'background_color' => '#929AD3',
// ]
// ),
// ];
// }
// }
