<?php

namespace YayMail\TemplateLibrary\Templates\Processing;

use YayMail\Abstracts\BaseTemplate;
use YayMail\Elements\Button;
use YayMail\Elements\Column;
use YayMail\Elements\ColumnLayout;
use YayMail\Elements\FeaturedProducts;
use YayMail\Elements\Heading;
use YayMail\Elements\Logo;
use YayMail\Elements\SocialIcon;
use YayMail\Elements\Text;
use YayMail\Utils\SingletonTrait;

/**
 * Processing 8 template for customer_processing_order email.
 * Generated by tools/yaymail-template-gen — review/tweak values as needed.
 */
// class Processing8 extends BaseTemplate {
// use SingletonTrait;

// public function __construct() {
// parent::__construct();
// $this->id          = 'processing_order_v8';
// $this->email_type  = 'customer_processing_order';
// $this->name        = 'Processing 8';
// $this->description = 'Processing 8 template for Processing Order email.';
// $this->access      = 'free';
// $this->elements    = [
// ColumnLayout::get_object_data(
// 4,
// [
// 'children'         => [
// Column::get_object_data(
// 29,
// [
// 'children' => [
// Logo::get_object_data(
// [
// 'padding' => [
// 'top'    => '10',
// 'right'  => '10',
// 'bottom' => '10',
// 'left'   => '0',
// ],
// 'background_color' => '#00000000',
// 'src'     => 'https://images.wpbrandy.com/uploads/woo-green-logo-1.png',
// 'align'   => 'left',
// 'width'   => '116',
// 'alt'     => 'Store logo',
// ]
// ),
// ],
// ]
// ),
// Column::get_object_data(
// 34.49,
// [
// 'children' => [
// Text::get_object_data(
// [
// 'padding'     => [
// 'top'    => '15',
// 'right'  => '0',
// 'bottom' => '15',
// 'left'   => '0',
// ],
// 'background_color' => '#000000',
// 'font_family' => '"Lucida Console", Monaco, monospace',
// 'text_color'  => '#ffffff',
// 'rich_text'   => '<p style="text-align: right"><span style="font-size: 14px;font-weight: 400">My Account</span></p>',
// ]
// ),
// ],
// ]
// ),
// Column::get_object_data(
// 27.76,
// [
// 'children' => [
// Text::get_object_data(
// [
// 'padding'     => [
// 'top'    => '15',
// 'right'  => '0',
// 'bottom' => '15',
// 'left'   => '0',
// ],
// 'background_color' => '#000000',
// 'font_family' => '"Lucida Console", Monaco, monospace',
// 'text_color'  => '#ffffff',
// 'rich_text'   => '<p style="text-align: center"><span style="font-size: 14px;font-weight: 400">Order Tracking</span></p>',
// ]
// ),
// ],
// ]
// ),
// Column::get_object_data(
// 8.75,
// [
// 'children' => [
// Text::get_object_data(
// [
// 'padding'     => [
// 'top'    => '15',
// 'right'  => '2',
// 'bottom' => '15',
// 'left'   => '0',
// ],
// 'background_color' => '#000000',
// 'font_family' => '"Lucida Console", Monaco, monospace',
// 'text_color'  => '#ffffff',
// 'rich_text'   => '<p style="text-align: right"><span style="font-size: 14px;font-weight: 400">Contact</span></p>',
// ]
// ),
// ],
// ]
// ),
// ],
// 'padding'          => [
// 'top'    => '20',
// 'right'  => '50',
// 'bottom' => '20',
// 'left'   => '50',
// ],
// 'background_color' => '#000000',
// ]
// ),
// ColumnLayout::get_object_data(
// 1,
// [
// 'children'         => [
// Column::get_object_data(
// 100,
// [
// 'children' => [
// Heading::get_object_data(
// [
// 'padding'     => [
// 'top'    => 60,
// 'right'  => '0',
// 'bottom' => 160,
// 'left'   => '0',
// ],
// 'background_color' => '#1A1A1A00',
// 'font_family' => 'Georgia, serif',
// 'text_color'  => '#d5f381',
// 'rich_text'   => '<p style="font-size: 56px;font-weight: bold;line-height: 1 !important;margin: 0"><span style="font-size: 120px">BLACK</span><br /><span style="font-size: 120px">FRIDAY</span></p>',
// ]
// ),
// Text::get_object_data(
// [
// 'padding'     => [
// 'top'    => '0',
// 'right'  => 30,
// 'bottom' => 0,
// 'left'   => '0',
// ],
// 'background_color' => '#1A1A1A00',
// 'font_family' => '"Arial Black", Gadget, sans-serif',
// 'text_color'  => '#ffffff',
// 'rich_text'   => '<p style="text-align: right"><span style="font-size: 96px;font-weight: 800">-50%</span></p>',
// ]
// ),
// Button::get_object_data(
// [
// 'padding'     => [
// 'top'    => '0',
// 'right'  => '0',
// 'bottom' => '0',
// 'left'   => '0',
// ],
// 'background_color' => '#1A1A1A00',
// 'align'       => 'right',
// 'width'       => '50%',
// 'height'      => 19,
// 'button_background_color' => '#d5f381',
// 'text_color'  => '#000000',
// 'border_radius' => [
// 'top_left' => '0',
// 'top_right' => '0',
// 'bottom_right' => '0',
// 'bottom_left' => '0',
// ],
// 'text'        => 'SHOP NOW',
// 'font_size'   => 16,
// 'weight'      => '700',
// 'font_family' => 'Georgia, serif',
// ]
// ),
// ],
// ]
// ),
// ],
// 'padding'          => [
// 'top'    => 0,
// 'right'  => '50',
// 'bottom' => 27,
// 'left'   => '50',
// ],
// 'background_color' => '#1A1A1A',
// 'background_image' => [
// 'url'         => 'https://images.wpbrandy.com/uploads/processing-8-img-3.webp',
// 'position'    => 'bottom_left',
// 'x_position'  => -1,
// 'y_position'  => 100,
// 'repeat'      => 'no-repeat',
// 'size'        => 'custom',
// 'custom_size' => 83,
// ],
// ]
// ),
// ColumnLayout::get_object_data(
// 1,
// [
// 'children'         => [
// Column::get_object_data(
// 100,
// [
// 'children' => [
// FeaturedProducts::get_object_data(
// [
// 'padding'     => [
// 'top'    => 0,
// 'right'  => '0',
// 'bottom' => 0,
// 'left'   => '0',
// ],
// 'background_color' => '#00000000',
// 'text_color'  => '#ffffff',
// 'font_family' => 'Georgia, serif',
// 'showing_items' => [
// 'product_image',
// 'product_name',
// 'product_price',
// 'top_content',
// ],
// 'top_content' => '<p style="text-align: center;"><span style="font-size: 24px;"><strong>You might also like to try</strong></span></p>
// <p style="text-align: center;"><span style="font-weight: 400;">Check out other products in our store that you might like</span></p>',
// 'sale_price_color' => '#ffffff',
// 'regular_price_color' => '#B0B0B0',
// 'products_per_row' => '2',
// 'number_of_products' => 4,
// ]
// ),
// Button::get_object_data(
// [
// 'padding'     => [
// 'top'    => 10,
// 'right'  => '0',
// 'bottom' => 10,
// 'left'   => '0',
// ],
// 'background_color' => '#0F162900',
// 'button_background_color' => '#d5f381',
// 'text_color'  => '#1a1a1a',
// 'border_radius' => [
// 'top_left' => '0',
// 'top_right' => '0',
// 'bottom_right' => '0',
// 'bottom_left' => '0',
// ],
// 'text'        => 'View all products',
// 'font_size'   => '14',
// 'weight'      => '700',
// 'font_family' => '"Rethink Sans","Helvetica Neue",Helvetica,Roboto,Arial,sans-serif',
// ]
// ),
// ],
// ]
// ),
// ],
// 'padding'          => [
// 'top'    => '48',
// 'right'  => '50',
// 'bottom' => '48',
// 'left'   => '50',
// ],
// 'background_color' => '#0F1629',
// 'background_image' => [
// 'url'      => 'https://images.wpbrandy.com/uploads/processing-8-img-2.png',
// 'position' => 'center_center',
// 'size'     => 'cover',
// 'repeat'   => 'repeat',
// ],
// ]
// ),
// ColumnLayout::get_object_data(
// 1,
// [
// 'children'         => [
// Column::get_object_data(
// 100,
// [
// 'children' => [
// Text::get_object_data(
// [
// 'padding'     => [
// 'top'    => '0',
// 'right'  => '0',
// 'bottom' => '0',
// 'left'   => '0',
// ],
// 'background_color' => '#ffffff',
// 'font_family' => 'Georgia, serif',
// 'text_color'  => '#1a1a1a',
// 'rich_text'   => '<p style="text-align: center"><span style="font-size: 14px">For questions, contact <u>hi@yourwoostore.com</u>, visit our <u>FAQs</u>, or <u>chat</u> with us during operating hours for account support</span></p>',
// ]
// ),
// SocialIcon::get_object_data(
// [
// 'padding'    => [
// 'top'    => '20',
// 'right'  => '0',
// 'bottom' => '16',
// 'left'   => '0',
// ],
// 'background_color' => '#ffffff',
// 'width_icon' => '32',
// 'spacing'    => '12',
// 'icon_list'  => [
// [
// 'icon' => 'facebook',
// 'url'  => '#',
// ],
// [
// 'icon' => 'instagram',
// 'url'  => '#',
// ],
// [
// 'icon' => 'tiktok',
// 'url'  => '#',
// ],
// [
// 'icon' => 'youtube',
// 'url'  => '#',
// ],
// ],
// ]
// ),
// Text::get_object_data(
// [
// 'padding'     => [
// 'top'    => '0',
// 'right'  => '0',
// 'bottom' => '0',
// 'left'   => '0',
// ],
// 'background_color' => '#ffffff',
// 'font_family' => 'Georgia, serif',
// 'text_color'  => '#1a1a1a',
// 'rich_text'   => '<p style="text-align: center"><span style="font-size: 12px">© 2021 WooCommerce</span></p>',
// ]
// ),
// ],
// ]
// ),
// ],
// 'padding'          => [
// 'top'    => '32',
// 'right'  => '50',
// 'bottom' => '32',
// 'left'   => '50',
// ],
// 'background_color' => '#ffffff',
// ]
// ),
// ];
// }
// }
