<?php

namespace YayMail\TemplateLibrary\Templates\Processing;

use YayMail\Abstracts\BaseTemplate;
use YayMail\Elements\BillingAddress;
use YayMail\Elements\Button;
use YayMail\Elements\Column;
use YayMail\Elements\ColumnLayout;
use YayMail\Elements\Divider;
use YayMail\Elements\FeaturedProducts;
use YayMail\Elements\Heading;
use YayMail\Elements\Logo;
use YayMail\Elements\OrderDetails;
use YayMail\Elements\OrderProgress;
use YayMail\Elements\ShippingAddress;
use YayMail\Elements\SocialIcon;
use YayMail\Elements\Text;
use YayMail\Utils\SingletonTrait;

/**
 * Tech Journey template for customer_processing_order email.
 * Generated by tools/yaymail-template-gen — review/tweak values as needed.
 */
class TechJourney extends BaseTemplate {
    use SingletonTrait;

    public function __construct() {
        parent::__construct();
        $this->id                = 'processing_order_v15';
        $this->email_type        = 'customer_processing_order';
        $this->name              = 'Tech Journey';
        $this->description       = 'Modern order tracking with tech products.';
        $this->categories        = [ 'Electronics' ];
        $this->template_settings = [
            'text_link_color' => '#000000',
        ];
        $this->access            = 'free';
        $this->elements          = [
            ColumnLayout::get_object_data(
                4,
                [
                    'children'               => [
                        Column::get_object_data(
                            29,
                            [
                                'children' => [
                                    Logo::get_object_data(
                                        [
                                            'padding' => [
                                                'top'    => '10',
                                                'right'  => '10',
                                                'bottom' => '10',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'src'     => 'https://images.wpbrandy.com/uploads/woo-black-logo.png',
                                            'align'   => 'left',
                                            'width'   => '116',
                                            'url'     => '#',
                                            'alt'     => 'Store logo',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            34.49,
                            [
                                'children' => [
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '15',
                                                'right'  => '0',
                                                'bottom' => '15',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'border'      => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'font_family' => '"Outfit", "DM Sans", sans-serif',
                                            'text_color'  => '#1a1a1a',
                                            'rich_text'   => '<p style="text-align: right"><span style="font-size: 16px">My Account</span></p>',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            27.76,
                            [
                                'children' => [
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '15',
                                                'right'  => '0',
                                                'bottom' => '15',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'border'      => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'font_family' => '"Outfit", "DM Sans", sans-serif',
                                            'text_color'  => '#1a1a1a',
                                            'rich_text'   => '<p style="text-align: center"><span style="font-size: 16px">Order Tracking</span></p>',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            8.75,
                            [
                                'children' => [
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '15',
                                                'right'  => '2',
                                                'bottom' => '15',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'border'      => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'font_family' => '"Outfit", "DM Sans", sans-serif',
                                            'text_color'  => '#1a1a1a',
                                            'rich_text'   => '<p style="text-align: right"><span style="font-size: 16px">Contact</span></p>',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'column_width'           => [],
                    'column_spacing'         => '0',
                    'responsive_on_mobile'   => false,
                    'vertical_align'         => 'top',
                    'padding'                => [
                        'top'    => '15',
                        'right'  => '50',
                        'bottom' => '15',
                        'left'   => '50',
                    ],
                    'border'                 => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'          => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'background_color'       => '#ffffff',
                    'background_image'       => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                    'inner_border_radius'    => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'inner_background_color' => '#ffffff00',
                ]
            ),
            ColumnLayout::get_object_data(
                1,
                [
                    'children'               => [
                        Column::get_object_data(
                            100,
                            [
                                'children' => [
                                    Heading::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => '12',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'border'      => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'font_family' => '"Outfit", "DM Sans", sans-serif',
                                            'text_color'  => '#000000',
                                            'rich_text'   => '<h1 style="font-size: 40px;font-weight: bold;line-height: 1.15 !important;margin: 0;color: #000000"><span style="font-size: 36px">Thanks for Your Order!</span></h1>',
                                        ]
                                    ),
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => '0',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'border'      => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'font_family' => '"Outfit", "DM Sans", sans-serif',
                                            'text_color'  => '#1a1a1a',
                                            'rich_text'   => '<p><span style="font-size: 14px">Order #[yaymail_order_id is_plain="true"] • Placed on [yaymail_order_date]</span></p>
                                                <p><span style="font-size: 14px">Status: Processing</span></p>',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'column_width'           => [],
                    'column_spacing'         => '0',
                    'responsive_on_mobile'   => false,
                    'vertical_align'         => 'top',
                    'padding'                => [
                        'top'    => '40',
                        'right'  => '50',
                        'bottom' => '40',
                        'left'   => '50',
                    ],
                    'border'                 => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'          => [
                        'top_left'     => 0,
                        'top_right'    => 0,
                        'bottom_left'  => 0,
                        'bottom_right' => 10,
                    ],
                    'background_color'       => '#ffffff',
                    'background_image'       => [
                        'url'      => 'https://images.wpbrandy.com/uploads/techjourney-background.png',
                        'position' => 'default',
                        'repeat'   => 'no-repeat',
                        'size'     => 'cover',
                    ],
                    'inner_border_radius'    => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'inner_background_color' => '#ffffff00',
                ]
            ),
            ColumnLayout::get_object_data(
                1,
                [
                    'children'               => [
                        Column::get_object_data(
                            100,
                            [
                                'children' => [
                                    OrderProgress::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '24',
                                                'right'  => 20,
                                                'bottom' => '24',
                                                'left'   => 20,
                                            ],
                                            'background_color' => '#ffffff',
                                            'display_style' => 'filled_bar',
                                            'current_step_index' => 1,
                                            'connector_height' => '3',
                                            'connector_active_color' => '#e2e6ee66',
                                            'connector_inactive_color' => '#e2e6ee66',
                                            'label_active_color' => '#000000',
                                            'label_inactive_color' => '#1a1a1a',
                                            'icon_size'   => '24',
                                            'filled_bar_icon_border_radius' => '50',
                                            'label_font_size' => '14',
                                            'font_family' => '"Outfit", "DM Sans", sans-serif',
                                            'steps'       => [
                                                [
                                                    'title' => 'Ordered',
                                                    'image_url' => 'https://images.wpbrandy.com/uploads/black-check.png',
                                                    'image_bg_color' => '#c0ff7c',
                                                    'icon_border_color' => '#000000',
                                                    'icon_border_style' => 'solid',
                                                    'icon_border_width' => 2,
                                                ],
                                                [
                                                    'title' => 'Processing',
                                                    'image_url' => 'https://images.wpbrandy.com/uploads/black-dot.png',
                                                    'image_bg_color' => '#c0ff7c',
                                                    'icon_border_color' => '#000000',
                                                    'icon_border_style' => 'solid',
                                                    'icon_border_width' => 2,
                                                ],
                                                [
                                                    'title' => 'Completed',
                                                    'image_url' => 'https://images.wpbrandy.com/uploads/white-circle.png',
                                                    'image_bg_color' => '#ffffff',
                                                    'icon_border_color' => '#dedede',
                                                    'icon_border_style' => 'dashed',
                                                    'icon_border_width' => 3,
                                                ],
                                            ],
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'all',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#00000014',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'column_width'           => [],
                    'column_spacing'         => '0',
                    'responsive_on_mobile'   => false,
                    'vertical_align'         => 'top',
                    'padding'                => [
                        'top'    => '15',
                        'right'  => 30,
                        'bottom' => '15',
                        'left'   => 30,
                    ],
                    'border'                 => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'          => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'background_color'       => '#fff',
                    'background_image'       => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                    'inner_border_radius'    => [
                        'top_left'     => 12,
                        'top_right'    => 12,
                        'bottom_left'  => 12,
                        'bottom_right' => 12,
                    ],
                    'inner_background_color' => '#ffffff00',
                ]
            ),
            Text::get_object_data(
                [
                    'padding'          => [
                        'top'    => 20,
                        'right'  => 30,
                        'bottom' => 10,
                        'left'   => 30,
                    ],
                    'background_color' => '#ffffff',
                    'border'           => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'font_family'      => '"Outfit", "DM Sans", sans-serif',
                    'text_color'       => '#1a1a1a',
                    'rich_text'        => '<p><span style="font-size: 18px">Hi </span><strong style="font-size: 18px">[yaymail_billing_first_name]</strong><span style="font-size: 18px">,</span></p>
                        </br>
                        <p><span style="font-size: 16px">Thank you for shopping with [yaymail_site_name]!</span></p>
                        </br>
                        <p><span style="white-space: pre-wrap;font-size: 16px">We\'ve received your order and are getting it ready. You can review your order details below or track its progress anytime.</span></p>',
                ]
            ),
            Button::get_object_data(
                [
                    'padding'                 => [
                        'top'    => 20,
                        'right'  => 30,
                        'bottom' => 20,
                        'left'   => 30,
                    ],
                    'background_color'        => '#ffffff',
                    'button_type'             => 'default',
                    'align'                   => 'left',
                    'width'                   => 'custom',
                    'custom_width'            => 38,
                    'height'                  => 24,
                    'button_padding'          => [
                        'top'    => '12',
                        'right'  => '20',
                        'bottom' => '12',
                        'left'   => '20',
                    ],
                    'button_background_color' => '#c0ff7c',
                    'text_color'              => '#1a1a1a',
                    'border'                  => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'           => [
                        'top_left'     => 12,
                        'top_right'    => 12,
                        'bottom_right' => 12,
                        'bottom_left'  => 12,
                    ],
                    'text'                    => 'View Order',
                    'url'                     => '[yaymail_order_url]',
                    'font_size'               => '16',
                    'weight'                  => '600',
                    'font_family'             => '"Outfit", "DM Sans", sans-serif',
                ]
            ),
            OrderDetails::get_object_data(
                [
                    'rich_text'               => '[yaymail_order_details]',
                    'payment_instructions'    => '[yaymail_payment_instructions]',
                    'padding'                 => [
                        'top'    => '15',
                        'right'  => 20,
                        'bottom' => '15',
                        'left'   => 20,
                    ],
                    'background_color'        => '#ffffff',
                    'border'                  => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'layout_type'             => 'legacy',
                    'title'                   => '<p><span style="font-size: 24px;font-weight: 600">Order Summary</span></p>',
                    'title_color'             => '#000000',
                    'text_color'              => '#1a1a1a',
                    'border_color'            => '#1a1a1a',
                    'font_family'             => '"Outfit", "DM Sans", sans-serif',
                    'table_content_font_size' => 16,
                    'table_heading_font_size' => 16,
                    'show_table_header'       => true,
                    'product_title'           => 'Product',
                    'cost_title'              => 'Cost',
                    'quantity_title'          => 'Quantity',
                    'price_title'             => 'Price',
                    'cart_subtotal_title'     => 'Subtotal:',
                    'payment_method_title'    => 'Payment method:',
                    'order_total_title'       => 'Total:',
                    'order_note_title'        => 'Note:',
                    'shipping_title'          => 'Shipping: [yaymail_shipping_method]',
                    'discount_title'          => 'Discount:',
                    'custom_footer_rows'      => [],
                ]
            ),
            ColumnLayout::get_object_data(
                2,
                [
                    'children'               => [
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    ShippingAddress::get_object_data(
                                        [
                                            'padding'      => [
                                                'top'    => '15',
                                                'right'  => 20,
                                                'bottom' => '15',
                                                'left'   => 20,
                                            ],
                                            'background_color' => '#fff',
                                            'layout_type'  => 'modern',
                                            'title_color'  => '#1a1a1a',
                                            'text_color'   => '#636363',
                                            'border_color' => '#e5e5e5',
                                            'font_family'  => '"Outfit", "DM Sans", sans-serif',
                                            'title'        => '<p><span style="font-size: 18px;font-weight: 600">Shipping Address</span></p>',
                                            'shipping_content_font_size' => 14,
                                            'shipping_content_alignment' => 'left',
                                            'shipping_content_text_format' => [
                                                'bold'   => false,
                                                'italic' => false,
                                                'underline' => false,
                                            ],
                                            'rich_text'    => '[yaymail_shipping_address]',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'all',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#1a1a1a',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                        Column::get_object_data(
                            50,
                            [
                                'children' => [
                                    BillingAddress::get_object_data(
                                        [
                                            'padding'      => [
                                                'top'    => '15',
                                                'right'  => 20,
                                                'bottom' => '15',
                                                'left'   => 10,
                                            ],
                                            'background_color' => '#fff',
                                            'layout_type'  => 'modern',
                                            'title_color'  => '#1a1a1a',
                                            'text_color'   => '#636363',
                                            'border_color' => '#e5e5e5',
                                            'font_family'  => '"Outfit", "DM Sans", sans-serif',
                                            'title'        => '<p><span style="font-size: 18px;font-weight: 600">Billing Address</span></p>',
                                            'billing_content_font_size' => '14',
                                            'billing_content_alignment' => 'left',
                                            'billing_content_text_format' => [
                                                'bold'   => false,
                                                'italic' => false,
                                                'underline' => false,
                                            ],
                                            'rich_text'    => '[yaymail_billing_address]',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'all',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#1a1a1a',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'column_width'           => [],
                    'column_spacing'         => 20,
                    'responsive_on_mobile'   => false,
                    'vertical_align'         => 'top',
                    'padding'                => [
                        'top'    => '15',
                        'right'  => 20,
                        'bottom' => '15',
                        'left'   => 20,
                    ],
                    'border'                 => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'          => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'background_color'       => '#fff',
                    'background_image'       => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                    'inner_border_radius'    => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'inner_background_color' => '#ffffff00',
                ]
            ),
            Text::get_object_data(
                [
                    'padding'          => [
                        'top'    => '15',
                        'right'  => 20,
                        'bottom' => '15',
                        'left'   => 20,
                    ],
                    'background_color' => '#fff',
                    'border'           => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'font_family'      => '"Outfit", "DM Sans", sans-serif',
                    'text_color'       => '#1a1a1a',
                    'rich_text'        => '<p><span style="font-size: 16px">Thanks again for shopping with us! If there\'s anything wrong with your order, please contact our support team within 7 days and we\'ll be happy to help.</span></p>',
                ]
            ),
            Text::get_object_data(
                [
                    'padding'          => [
                        'top'    => '15',
                        'right'  => 20,
                        'bottom' => '15',
                        'left'   => 20,
                    ],
                    'background_color' => '#fff',
                    'border'           => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'font_family'      => '"Outfit", "DM Sans", sans-serif',
                    'text_color'       => '#1a1a1a',
                    'rich_text'        => '<p><span style="font-size: 16px">Best regards,</span></p>
                        <p><span style="font-size: 16px">The <strong>[yaymail_site_name]</strong> Team</span></p>',
                ]
            ),
            Divider::get_object_data(
                [
                    'align'            => 'center',
                    'padding'          => [
                        'top'    => '15',
                        'right'  => 20,
                        'bottom' => '15',
                        'left'   => 20,
                    ],
                    'width'            => '100',
                    'height'           => 4,
                    'background_color' => '#fff',
                    'divider_color'    => '#1a1a1a',
                    'divider_type'     => 'solid',
                ]
            ),
            FeaturedProducts::get_object_data(
                [
                    'padding'                     => [
                        'top'    => 40,
                        'right'  => 20,
                        'bottom' => 60,
                        'left'   => 20,
                    ],
                    'background_color'            => '#ffffff',
                    'text_color'                  => '#1a1a1a',
                    'font_family'                 => '"Outfit", "DM Sans", sans-serif',
                    'showing_items'               => [
                        'top_content',
                        'product_image',
                        'product_name',
                        'product_price',
                        'buy_button',
                    ],
                    'top_content'                 => '<p style="text-align: center;"><span style="font-size: 24px; font-weight: bold;">You May Also Like</span></p>
                        <p style="text-align: center;">Discover more products picked for you.</p>
                        </br>',
                    'sale_price_color'            => '#595f65',
                    'regular_price_color'         => '#808080',
                    'buy_button_label'            => 'Shop Now',
                    'buy_button_background_color' => '#c0ff7c',
                    'buy_button_text_color'       => '#1a1a1a',
                    'products_per_row'            => '3',
                    'product_type'                => 'newest',
                    'categories'                  => [],
                    'tags'                        => [],
                    'products'                    => [],
                    'sorted_by'                   => 'none',
                    'number_of_products'          => 3,
                ]
            ),
            ColumnLayout::get_object_data(
                1,
                [
                    'children'               => [
                        Column::get_object_data(
                            100,
                            [
                                'children' => [
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => '0',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'border'      => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'font_family' => '"Outfit", "DM Sans", sans-serif',
                                            'text_color'  => '#ffffff',
                                            'rich_text'   => '<p style="text-align: center"><span style="font-size: 16px">For questions, contact <u>hi@yourwoostore.com</u>, visit our <u>FAQs</u>, or <u>chat</u> with us during operating hours for account support</span></p>',
                                        ]
                                    ),
                                    SocialIcon::get_object_data(
                                        [
                                            'padding'    => [
                                                'top'    => '20',
                                                'right'  => '0',
                                                'bottom' => '12',
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'align'      => 'center',
                                            'width_icon' => '32',
                                            'spacing'    => '12',
                                            'theme'      => 'Colorful',
                                            'icon_list'  => [
                                                [
                                                    'icon' => 'facebook',
                                                    'url'  => '#',
                                                ],
                                                [
                                                    'icon' => 'instagram',
                                                    'url'  => '#',
                                                ],
                                                [
                                                    'icon' => 'tiktok',
                                                    'url'  => '#',
                                                ],
                                                [
                                                    'icon' => 'youtube',
                                                    'url'  => '#',
                                                ],
                                            ],
                                        ]
                                    ),
                                    Text::get_object_data(
                                        [
                                            'padding'     => [
                                                'top'    => '0',
                                                'right'  => '0',
                                                'bottom' => 0,
                                                'left'   => '0',
                                            ],
                                            'background_color' => '#ffffff00',
                                            'border'      => [
                                                'side'   => 'none',
                                                'width'  => '1',
                                                'style'  => 'solid',
                                                'color'  => '#e5e5e5',
                                                'custom' => [
                                                    'top'  => '1',
                                                    'right' => '1',
                                                    'bottom' => '1',
                                                    'left' => '1',
                                                ],
                                            ],
                                            'font_family' => '"Outfit", "DM Sans", sans-serif',
                                            'text_color'  => '#ffffff',
                                            'rich_text'   => '<p style="text-align: center"><span style="font-size: 12px">© 2026 [yaymail_site_name]. All rights reserved.</span></p>',
                                        ]
                                    ),
                                ],
                                'border'   => [
                                    'side'   => 'none',
                                    'width'  => '1',
                                    'style'  => 'solid',
                                    'color'  => '#e5e5e5',
                                    'custom' => [
                                        'top'    => '1',
                                        'right'  => '1',
                                        'bottom' => '1',
                                        'left'   => '1',
                                    ],
                                ],
                            ]
                        ),
                    ],
                    'column_width'           => [],
                    'column_spacing'         => '0',
                    'responsive_on_mobile'   => false,
                    'vertical_align'         => 'top',
                    'padding'                => [
                        'top'    => 40,
                        'right'  => 40,
                        'bottom' => 40,
                        'left'   => 40,
                    ],
                    'border'                 => [
                        'side'   => 'none',
                        'width'  => '1',
                        'style'  => 'solid',
                        'color'  => '#e5e5e5',
                        'custom' => [
                            'top'    => '1',
                            'right'  => '1',
                            'bottom' => '1',
                            'left'   => '1',
                        ],
                    ],
                    'border_radius'          => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'background_color'       => '#1a1a1a',
                    'background_image'       => [
                        'url'        => '',
                        'position'   => 'default',
                        'x_position' => 0,
                        'y_position' => 0,
                        'repeat'     => 'default',
                        'size'       => 'default',
                    ],
                    'inner_border_radius'    => [
                        'top_left'     => '0',
                        'top_right'    => '0',
                        'bottom_left'  => '0',
                        'bottom_right' => '0',
                    ],
                    'inner_background_color' => '#ffffff00',
                ]
            ),
        ];
    }
}
