<?php
/**
 * Plugin adapter for YayMail - WooCommerce Email Customizer.
 * Generated by yaycommerce-init. Edit values as needed.
 */

defined( 'ABSPATH' ) || exit;

class YaymailPluginAdapter implements \YayMailScoped\YayCommerce\AdminShell\Contracts\PluginMenuAdapter, \YayMailScoped\YayCommerce\AdminShell\Contracts\AddonHostAdapter {
    public function get_menu_title(): string {
        return 'YayMail'; }
    public function get_page_title(): string {
        return 'YayMail - WooCommerce Email Customizer'; }
    public function get_menu_slug(): string {
        return 'yaymail-settings'; }
    public function get_settings_page_callback(): ?callable {
        // Render is registered by admin-shell (PluginSubmenu); avoid duplicate add_submenu_page in SettingsPage.
        return static function (): void {
            include_once YAYMAIL_PLUGIN_PATH . 'templates/pages/settings.php';
        };
    }
    public function get_settings_page_position(): ?int {
        return 10; }
    public function get_capability(): string {
        return 'manage_woocommerce'; }
    public function get_plugin_basename(): string {
        return YAYMAIL_PLUGIN_BASENAME; }
    public function get_settings_label(): string {
        return 'Start Customizing'; }
    public function get_docs_url(): string {
        return 'https://docs.yaycommerce.com/yaymail/'; }
    public function get_pro_url(): string {
        return 'https://yaycommerce.com/yaymail-woocommerce-email-customizer/'; }

    // --- Addon host ---
    public function get_addon_licensing_filter(): string {
        return 'yaymail_available_licensing_plugins'; }
}
